%    Copyright: 	NTNU, Trondheim, Norway
%    Licensed under GPL-3.0
%    Created:  	2014-2017	Torstein Aarseth Bø <torstein.bo@sintef.no>

function VR = busVoltageVRnonZeroEr(ei,er,p,q,zi,zr)
%BUSVOLTAGEVRNONZEROER
%    VR = BUSVOLTAGEVRNONZEROER(EI,ER,P,Q,ZI,ZR)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    11-Jun-2014 16:56:08

t2 = ei.^2;
t3 = er.^2;
t4 = sqrt(3.0);
t5 = t2+t3;
t6 = 1.0./t5;
t7 = p.^2;
t8 = zi.^2;
t9 = q.^2;
t10 = zr.^2;
t11 = t2.^2;
t12 = t11.*3.0;
t13 = t3.^2;
t14 = t13.*3.0;
t15 = t2.*t3.*6.0;
t16 = p.*q.*zi.*zr.*(8.0./3.0);
t17 = t12+t14+t15+t16-t7.*t8.*(4.0./3.0)-t9.*t10.*(4.0./3.0)-p.*t2.*zr.*4.0-p.*t3.*zr.*4.0-q.*t2.*zi.*4.0-q.*t3.*zi.*4.0;
t18 = sqrt(t17);
t19 = er.*t3.*t4.*3.0;
t20 = er.*t2.*t4.*3.0;
t21 = ei.*p.*t4.*zi.*2.0;
VR = [t6.*(t19+t20+t21-er.*t18.*3.0-ei.*q.*t4.*zr.*2.0).*(1.0./6.0);t6.*(t19+t20+t21+er.*t18.*3.0-ei.*q.*t4.*zr.*2.0).*(1.0./6.0)];
