%    Copyright: 	NTNU, Trondheim, Norway
%    Licensed under GPL-3.0
%    Created:  	2014-2017	Torstein Aarseth Bø <torstein.bo@sintef.no>

function out1 = busVoltageIsValid(ei,er,p,q,zi,zr)
%BUSVOLTAGEISVALID
%    OUT1 = BUSVOLTAGEISVALID(EI,ER,P,Q,ZI,ZR)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    11-Jun-2014 16:56:09

t2 = er.^2;
t3 = ei.^2;
out1 = (0.0 <= t2.*1.0./(t2+t3).^2.*(p.^2.*zi.^2.*4.0+q.^2.*zr.^2.*4.0-t2.*t3.*1.8e1-t2.^2.*9.0-t3.^2.*9.0+p.*t2.*zr.*1.2e1+p.*t3.*zr.*1.2e1+q.*t2.*zi.*1.2e1+q.*t3.*zi.*1.2e1-p.*q.*zi.*zr.*8.0).*(-1.0./3.0));
