%    Copyright: 	NTNU, Trondheim, Norway
%    Licensed under GPL-3.0
%    Created:  	2014-2017	Torstein Aarseth Bø <torstein.bo@sintef.no>

function VR = busVoltageVRlowEr(ei,er,p,q,vi,zi,zr)
%BUSVOLTAGEVRLOWER
%    VR = BUSVOLTAGEVRLOWER(EI,ER,P,Q,VI,ZI,ZR)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    11-Jun-2014 16:55:14

t2 = sqrt(3.0);
VR = (er.*vi+p.*t2.*zi.*(1.0./3.0)-q.*t2.*zr.*(1.0./3.0))./ei;
