/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Mon Aug  4 22:56:12 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include "GetIdealNozzleFlow.h"
#include "GetHTCoeffHTX.h"
#include "GetThdynCombGasZachV1.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void AirWaterCoolerPTF_Outputs_wrapper(const real_T *pu,
                          const real_T *Tu,
                          const real_T *Fu,
                          const real_T *pd,
                          const real_T *Td,
                          const real_T *Fd,
                          const real_T *T_cw,
                          real_T *dmu,
                          real_T *deu,
                          real_T *dmbu,
                          real_T *dmd,
                          real_T *ded,
                          real_T *dmbd  , 
                          const real_T  *fs, const int_T  p_width0, 
                          const real_T  *Cd, const int_T  p_width1, 
                          const real_T  *A_air_path, const int_T  p_width2, 
                          const real_T  *dm_cw, const int_T  p_width3, 
                          const real_T  *coeff_T_cw_K, const int_T  p_width4, 
                          const real_T  *Cp_cw, const int_T  p_width5, 
                          const real_T  *D_cw_pipe,  const int_T p_width6)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
// parameters
//	double fs;              //Stoichiometric fuel-air ratio
//  double Cd;              //Discharge coefficient of the charge air cooler
//	double A_air_path;      //Effective area of air passage
//  double dm_cw;           //mass flow of coolant
//  double coeff_T_cw_K[2]; //HT coefficient correction factor WRT T_cw
//	double Cp_cw; 			//Heat capacity of coolant
//  double D_cw_pipe;		//Diameter of the tube in the cooler


double aa, a, aCR;          //pressure ratio(up/down, in/out), 
                            //critical pressure ratio
double d;                   //flow direction
double gamma1;
double p_in, T_in, F_in;    //inlet pressure, temperature, FA equivalent ratio
double p_out, T_out;        //outlet pressure, temperature
double hu,su,uu,Ru,RFu,Rpu,RTu,uFu,upu,uTu,sFu,spu,sTu,Cpu,Cvu,Ku;
double hd,sd,ud,RFd,Rd,Rpd,RTd,uFd,upd,uTd,sFd,spd,sTd,Cpd,Cvd,Kd;
                            //thermodynamic properties of in/out gases
double alpha, K;            //convective heat transfer coefficient
                            //Effective heat transfer area
double T_out_temp, err_T_out, T_mean; 
                            //Variables for finding outlet temperature
double C, C1, C2, N, epsilon; //Variables for e-NTU model
double test1;
aa = *pu / *pd;
if (aa > 1) {
    p_in = *pu;      T_in = *Tu; 
    F_in= *Fu;	    p_out = *pd;
    a = 1/aa;         d = 1;
}
else {
	p_in = *pd;     T_in = *Td; 
    F_in = *Fd;    	p_out = *pu;
    a = aa;       d = -1;
}

GetThdynCombGasZachV1(p_in, T_in, F_in, fs[0], &Ru, &hu, &su, &uu, &RFu, 
        &Rpu, &RTu, &uFu, &upu, &uTu, &sFu, &spu, &sTu, &Cpu, &Cvu, &Ku);
gamma1 = (Ku - 1.0) / Ku;
aCR = pow(2.0 / (Ku + 1.0), 1.0 / gamma1);

if (a < aCR) {
    dmu[0] = Cd[0] * A_air_path[0] * p_in / sqrt(Ru * T_in) 
            * sqrt(Ku * pow(2.0/(Ku + 1.0), (Ku + 1.0)/(Ku - 1.0)));
} 
else {
    dmu[0] = Cd[0] * A_air_path[0] * p_in / sqrt(Ru * T_in) * 
            pow(a, 1.0 / Ku) * 
            sqrt(2.0 / gamma1 * (1.0 - pow(a, gamma1)));
}

dmu[0] = dmu[0]*d;
deu[0] = dmu[0] * hu;
dmbu[0] = dmu[0]*(F_in*fs[0] / (1+F_in*fs[0]));

if (dmu[0] == 0) {
	T_out = T_in;
}
else {
    K = coeff_T_cw_K[0]*(*T_cw) + coeff_T_cw_K[1];
    T_out = T_in + 1;
	err_T_out = 1;
	while (err_T_out > 1e-3) {
        T_mean = (T_in - T_out)/(log(T_in) - log(T_out));
        C1 = fabs(dmu[0])*Cpu;
        C2 = dm_cw[0]*Cp_cw[0];
        C = C1/C2;
        alpha = GetHTCoeffHTX(p_in, fabs(dmu[0]), T_mean, D_cw_pipe[0], A_air_path[0]);
        N = K*alpha/C1;
        epsilon = 1 - exp((exp(-C*pow(N,0.78))-1)/(C*pow(N,-0.22)));
        T_out_temp = T_in - epsilon*(T_in - T_cw[0]);
	    err_T_out = abs(T_out - T_out_temp)/T_out;
	    T_out = T_out_temp;
    }
}
GetThdynCombGasZachV1(p_out, T_out, F_in, fs[0], &Rd, &hd, &sd, &ud, &RFd, 
        &Rpd, &RTd, &uFd, &upd, &uTd, &sFd, &spd, &sTd, &Cpd, &Cvd, &Kd);
dmd[0] = dmu[0];
ded[0] = hd*dmd[0];
dmbd[0] = dmbu[0];
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
