/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Jul 30 16:09:43 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 3
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void blowerFit_Outputs_wrapper(const real_T *pTF_u,
                          const real_T *pTF_d,
                          const real_T *blowerRun,
                          const real_T *mDotBlower,
                          real_T *dmEmb_u,
                          real_T *dmEmb_d,
                          real_T *powBlower  , 
                          const real_T  *effBlower, const int_T  p_width0, 
                          const real_T  *fs,  const int_T p_width1)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
double pu, pd, tu, td, fu, fd, pr, tdi;
double dmBlowerCorr;
double hu,su,uu,Ru,RFu,Rpu,RTu,uFu,upu,uTu,sFu,spu,sTu,Cpu,Cvu,Ku;
double hdi,sdi,udi,RFdi,Rdi,Rpdi,RTdi,uFdi,updi,uTdi,sFdi,spdi,sTdi,
        Cpdi,Cvdi,Kdi;


if (blowerRun[0] == 0) {
    dmEmb_u[0] = 0;
    dmEmb_u[1] = 0;
    dmEmb_u[2] = 0;
    dmEmb_d[0] = 0;
    dmEmb_d[1] = 0;
    dmEmb_d[2] = 0;
}
else {
    pu = pTF_u[0];  pd = pTF_d[0];
    tu = pTF_u[1];  td = pTF_d[1];
    fu = pTF_u[2];  fd = pTF_d[2];
    pr = pd / pu;
    dmBlowerCorr = mDotBlower[0]*blowerRun[0];
    dmEmb_u[0] = dmBlowerCorr*pu/1e5*sqrt(298.15/tu);
    dmEmb_u[2] = dmEmb_u[0]*fu*fs[0]/(1+fu*fs[0]);
    GetThdynCombGasZachV1(pu,tu,fu,fs[0],&Ru,&hu,&su,&uu,&RFu,&Rpu,&RTu,
            &uFu,&upu,&uTu,&sFu,&spu,&sTu,&Cpu,&Cvu,&Ku);
    dmEmb_u[1] = dmEmb_u[0]*hu;
    
    dmEmb_d[0] = dmEmb_u[0];
    dmEmb_d[2] = dmEmb_u[2];
    tdi = tu*pow(pr,((Ku-1)/Ku));
    GetThdynCombGasZachV1(pd,tdi,fu,fs[0],&Rdi,&hdi,&sdi,&udi,&RFdi,&Rpdi,
            &RTdi,&uFdi,&updi,&uTdi,&sFdi,&spdi,&sTdi,&Cpdi,&Cvdi,&Kdi);
    dmEmb_d[1] = dmEmb_d[0]*(hdi - hu)/effBlower[0];
    powBlower[0] = dmEmb_d[1];
    dmEmb_d[1] = dmEmb_u[1] + dmEmb_d[1];
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
