/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Jul 23 10:45:03 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void CombWiebe_Outputs_wrapper(const real_T *combState,
                          const real_T *phiComb,
                          const real_T *phiIg,
                          const real_T *mqf,
                          const real_T *omega,
                          real_T *dmEmb ,
			      const real_T  *xD,
                          const real_T  *hn, const int_T  p_width0, 
                          const real_T  *wiebePara, const int_T p_width1)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
double yp, ym, yl, yptomp, ymtomm, yltoml, df1dy, df2dy, df3dy, dmfNom, dmf;
const double pi = 3.14159265359;
if (*combState == 2) {
    yp = (*phiComb - *phiIg) / wiebePara[3];
    if (yp < 0) {
        yp = 0;
    }
    ym = (*phiComb - (*phiIg + wiebePara[2]))/wiebePara[4];
    if (ym < 0) {
        ym = 0;
    }
	yl = (*phiComb - (*phiIg + wiebePara[2]))/wiebePara[5];
    if (yl < 0) {
        yl = 0;
    }
	yptomp = pow(yp,wiebePara[6]);
	ymtomm = pow(ym,wiebePara[7]);
	yltoml = pow(yl,wiebePara[8]);
	df1dy = 6.9*(wiebePara[6] + 1)*yptomp*exp(-6.9*yp*yptomp) / wiebePara[3];
	df2dy = 6.9*(wiebePara[7] + 1)*ymtomm*exp(-6.9*ym*ymtomm) / wiebePara[4];
	df3dy = 6.9*(wiebePara[8] + 1)*yltoml*exp(-6.9*yl*yltoml) / wiebePara[5];
	dmfNom = wiebePara[0]*df1dy + wiebePara[1]*df2dy + (1-wiebePara[0] - wiebePara[1])*df3dy;
    dmf = *mqf*dmfNom*(*omega)*180/pi;
	dmEmb[0] = dmf;
    dmEmb[1] = *hn*dmf;
    dmEmb[2] = dmf;
}
else {
    dmEmb[0] = 0;
    dmEmb[1] = 0;
    dmEmb[2] = 0;
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  * Updates function
  *
  */
void CombWiebe_Update_wrapper(const real_T *combState,
                          const real_T *phiComb,
                          const real_T *phiIg,
                          const real_T *mqf,
                          const real_T *omega,
                          const real_T *dmEmb ,
                          real_T *xD, 
                          const real_T  *hn,  const int_T  p_width0,
                           const real_T *wiebePara, const int_T  p_width1)
{
  /* %%%-SFUNWIZ_wrapper_Update_Changes_BEGIN --- EDIT HERE TO _END */
xD[0] = *phiComb + *phiIg;
/* %%%-SFUNWIZ_wrapper_Update_Changes_END --- EDIT HERE TO _BEGIN */
}
