/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Jul 23 11:27:18 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void crankMechKinematic_Outputs_wrapper(const real_T *pCyl,
                          const real_T *omega,
                          const real_T *pScav,
                          real_T *dV,
                          real_T *Tq,
                          real_T *powInd,
                          real_T *phi ,
			   const real_T *xC,
                          const real_T  *phi0, const int_T  p_width0, 
                          const real_T  *B, const int_T  p_width1, 
                          const real_T  *stroke, const int_T  p_width2, 
                          const real_T  *lambdaCrank, const int_T p_width3)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
const double pi = 3.14159265359;
double m1, m2, m;


*phi = xC[0];

m1 = pow(*B,2)*pi/4;
m2 = *stroke/2*(sin(*phi) + *lambdaCrank*sin(*phi)*cos(*phi)/
                            sqrt(1 - pow(*lambdaCrank*sin(*phi),2))) + 1e-20;
m = m1*m2;
*Tq = m*(*pCyl - *pScav);
*dV = *omega * m;
*powInd = *pCyl * (*dV);
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  *  Derivatives function
  *
  */
void crankMechKinematic_Derivatives_wrapper(const real_T *pCyl,
                          const real_T *omega,
                          const real_T *pScav,
                          const real_T *dV,
                          const real_T *Tq,
                          const real_T *powInd,
                          const real_T *phi,
                          real_T *dx ,
                          real_T *xC, 
                          const real_T  *phi0,  const int_T  p_width0,
                          const real_T  *B,  const int_T  p_width1,
                          const real_T  *stroke,  const int_T  p_width2,
                           const real_T *lambdaCrank, const int_T  p_width3)
{
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_BEGIN --- EDIT HERE TO _END */
dx[0] = *omega;
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_END --- EDIT HERE TO _BEGIN */
}