/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sat Jul 19 10:05:31 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void GetExhVVLift_Outputs_wrapper(const real_T *phi,
                          const real_T *cAStartNom,
                          const real_T *dCALiftNom,
                          real_T *lift  , 
                          const real_T  *liftMax, const int_T  p_width0, 
                          const real_T  *cAStartRef, const int_T  p_width1, 
                          const real_T  *dCALiftUp, const int_T  p_width2, 
                          const real_T  *dCALiftDown, const int_T  p_width3, 
                          const real_T  *dCALiftTopRef, const int_T  p_width4, 
                          const real_T  *cAVVUpRef, const int_T  p_width5, 
                          const real_T  *cAVVDownRef, const int_T  p_width6, 
                          const real_T  *liftUpRef, const int_T  p_width7, 
                          const real_T  *liftDownRef,  const int_T p_width8)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
double cAStart, dCALift, dCATotal, phi360, cAVV; 
double pIn, pOut, tempIn, tempOut, fIn, fOut;
int i;
const double pi = 3.14159265359;

cAStart = *cAStartNom*(*cAStartRef);
dCALift = *dCALiftNom*(*dCALiftTopRef);	
dCATotal = *dCALiftUp + dCALift + *dCALiftDown;
phi360 = *phi*180.0/pi;
phi360 = (((int)(floor(phi360)) % 360)) + phi360 - floor(phi360) ;

if ((phi360 > cAStart) & (phi360 < (cAStart + dCATotal))) {
   cAVV = phi360 - cAStart;
   if (cAVV <= *dCALiftUp) {
       i = 0;
       while (cAVV > cAVVUpRef[i]) {
           i++;
       }
       *lift = liftUpRef[i] + (liftUpRef[i+1] - liftUpRef[i])*
               (cAVV - cAVVUpRef[i])/(cAVVUpRef[i+1] - cAVVUpRef[i]);
   }
   else {
       if (cAVV <= *dCALiftUp + dCALift) {
           *lift = 1;
       }
       else {
           if (cAVV <= *dCALiftUp + dCALift + *dCALiftDown) {
               cAVV = phi360 - (cAStart + *dCALiftUp + dCALift);
            i = 0;
            while (cAVV > cAVVDownRef[i]) {
                i++;
            }
            *lift = liftDownRef[i] + (liftDownRef[i+1] - liftDownRef[i])*
               (cAVV - cAVVDownRef[i])/(cAVVDownRef[i+1] - cAVVDownRef[i]);
           }
            else {
                *lift = 0;	
            }
       }
   }
    *lift = *liftMax*(*lift);
}
else {
    *lift = 0;	
}

/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
