/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Jul 23 15:00:01 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void GetExhVVArea_Outputs_wrapper(const real_T *lift,
                          const real_T *pIn,
                          const real_T *pOut,
                          real_T *aOpen,
                          real_T *Cd,
                          real_T *aEff  , 
                          const real_T  *Dv, const int_T  p_width0, 
                          const real_T  *beta, const int_T  p_width1, 
                          const real_T  *w, const int_T  p_width2, 
                          const real_T  *Dp, const int_T  p_width3, 
                          const real_T  *Ds, const int_T  p_width4, 
                          const real_T  *coeffCdCorrP, const int_T  p_width5, 
                          const real_T  *coeffCdCorrQ, const int_T  p_width6, 
                          const real_T  *coeffCdCorrPR,  const int_T p_width7)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
const double pi = 3.14159265359;
double L_Dv, pr;

if (*lift > 0) {
    if (*lift < (*w / (sin(*beta)*cos(*beta)))) {
        *aOpen = pi*(*lift)*cos(*beta)*
                (*Dv - 2*(*w) + *lift/2*sin(*beta*2));
    }
    else {
        if (*lift <= (sqrt((pow(*Dp,2) - pow(*Ds,2))/
                (4*(*Dv - *w)) - pow(*w,2)) + *w*tan(*beta))) {
            *aOpen = pi*(*Dv - *w)*
                    sqrt(pow(*lift - *w*tan(*beta),2) + pow(*w,2));
        }
        else {
            *aOpen = 0.25*pi*(pow(*Dp,2) - pow(*Ds,2));
        }
    }
    L_Dv = *lift/ *Dv;
    *Cd = ((L_Dv*coeffCdCorrP[0] + coeffCdCorrP[1])*L_Dv + coeffCdCorrP[2])
            / (((L_Dv + coeffCdCorrQ[0])*L_Dv + coeffCdCorrQ[1])*L_Dv + 
            coeffCdCorrQ[2]);
    if (*pIn > *pOut) {
        pr = *pIn / *pOut;
    }
    else {
        pr = *pOut / *pIn;
    }
    *Cd = *Cd*((coeffCdCorrPR[0]*pr + coeffCdCorrPR[1])*pr + coeffCdCorrPR[2]);
    *aEff = *aOpen * *Cd;
}
else {
    *aOpen = 0;
    *Cd = 0;
    *aEff = 0;
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
