/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Fri Jul 25 20:18:19 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void GetInportArea_Outputs_wrapper(const real_T *phi,
                          real_T *aOpen,
                          real_T *Cd,
                          real_T *aEff,
                          real_T *xP  , 
                          const real_T  *nStroke, const int_T  p_width0, 
                          const real_T  *aCrank, const int_T  p_width1, 
                          const real_T  *lambdaCrank, const int_T  p_width2, 
                          const real_T  *X, const int_T  p_width3, 
                          const real_T  *Y, const int_T  p_width4, 
                          const real_T  *r, const int_T  p_width5, 
                          const real_T  *nPort, const int_T  p_width6, 
                          const real_T  *stroke,  const int_T p_width7)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
double yOpen, theta, aR, lCrank;
const double pi = 3.14159265359;
lCrank = *aCrank / *lambdaCrank;       
*xP = *aCrank + lCrank - (*aCrank*cos(*phi) 
        + sqrt(pow(lCrank,2)-pow(*aCrank*sin(*phi),2)));
if (*xP > (*stroke - *Y)) {
    yOpen = *xP - (*stroke - *Y);
    if (yOpen < *r) {
        theta = asin((*r-yOpen)/(*r));
        *aOpen = (*X - 2*(*r))*yOpen + 0.5*pow(*r,2)*(pi/2-theta) 
                                   - 0.5*(*r - yOpen)*(*r)*cos(theta);
    }
    else {
         if (yOpen > (*Y - *r)) {
            yOpen = yOpen - (*Y - *r);
            if (yOpen/(*r) > 1) {
                theta = asin(1);
            }
            else {
                theta = asin(yOpen/(*r));
            }
            *aOpen = *X*(*Y-*r) - 0.43*pow(*r,2) + (*X-2*(*r))*yOpen 
                    + 0.5*pow(*r,2)*theta + 0.5*(*r)*cos(theta)*yOpen;
         }
         else {
            *aOpen = *X*yOpen - 0.43*pow(*r,2);
         }
    }
    aR = *aOpen / (*X*(*Y) - 0.86*pow(*r,2));   
    *Cd = ((((-5.408*aR + 15.9)*aR - 19.03)*aR + 11.39)*aR - 3.284)*aR + 1.143;
    *aOpen = *aOpen*(*nPort);
    if (*Cd > 0.98) {
       *Cd = 0.98;
    }
    *aEff = *aOpen * (*Cd);
}
else {
    *aEff = 0;
    *aOpen = 0;
    *Cd = 0;
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
