/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Jul 30 11:41:11 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include "GetIdealNozzleFlow.h"
#include "GetThdynCombGasZachV1.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void IdealNozzlePTF_Outputs_wrapper(const real_T *A_eff,
                          const real_T *pu,
                          const real_T *Tu,
                          const real_T *Fu,
                          const real_T *pd,
                          const real_T *Td,
                          const real_T *Fd,
                          real_T *dmu,
                          real_T *deu,
                          real_T *dmbu,
                          real_T *dmd,
                          real_T *ded,
                          real_T *dmbd, 
                           const real_T  *fs, const int_T p_width0)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
//parameters
//  double fs;      //Stoichiometric fuel-air ratio
//variables
double Cd, aa;   //Pressure ratio up/down and in/out, flow direction
double p_in, T_in, F_in, p_out; //Inlet pressure, temperature, FA equivalent ratio
double a;
//code
// First determine the flow direction

aa = *pu / *pd;
if (aa > 1) {
    p_in = *pu;      T_in = *Tu; 
    F_in= *Fu;	    p_out = *pd;
    a = 1;
}
else {
	p_in = *pd;     T_in = *Td; 
    F_in = *Fd;    	p_out = *pu;
    a = -1;
}
Cd = 1;
GetIdealNozzleFlowPTF(Cd, *A_eff, p_in, p_out, T_in, F_in, *fs, 
        dmu, deu, dmbu);    

*dmu = *dmu*a;
*deu = *deu*a;
*dmbu = *dmbu*a;
*dmd = *dmu;
*ded = *deu;
*dmbd = *dmbu;

/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
