/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Jun 18 12:56:57 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
#include "GetThdynCombGasZachV1.h"
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
 
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void InCylinderMV_Outputs_wrapper(const real_T *pu,
                          const real_T *Tu,
                          const real_T *Fu,
                          const real_T *pd,
                          const real_T *Td,
                          const real_T *Fd,
                          const real_T *omegae,
                          const real_T *throttle,
                          real_T *dmu,
                          real_T *deu,
                          real_T *dmbu,
                          real_T *dmd,
                          real_T *ded,
                          real_T *dmbd,
                          real_T *Tqe,
                          real_T *vol_eff ,
                          real_T *pe,
			   const real_T *xC,
                          const real_T  *fs, const int_T  p_width0, 
                          const real_T  *Vd, const int_T  p_width1, 
                          const real_T  *LHV, const int_T  p_width2, 
                          const real_T  *Pe_nom, const int_T  p_width3, 
                          const real_T  *SFC, const int_T  p_width4, 
                          const real_T  *vol_eff_coeff1, const int_T  p_width5, 
                          const real_T  *vol_eff_coeff2, const int_T  p_width6, 
                          const real_T  *T_pe, const int_T  p_width7, 
                          const real_T  *nstroke, const int_T  p_width8, 
                          const real_T  *m_f_cyc_max, const int_T  p_width9, 
                          const real_T  *C1, const int_T  p_width10, 
                          const real_T  *p_a_inf, const int_T  p_width11, 
                          const real_T  *Pe0, const int_T p_width12)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
//Parameters
//  double Vd;       //Displacement volume (m3)
//  double LHV;      //Lower heating value of the fuel (J/kg)
//  double Pe_nom;   //Rated shaft power (W)
//  double SFC[3];   //Quadratic SFC curve coefficient
//  double vol_eff_coeff1[3], vol_eff_coeff2[3]; 
       //Volumetric efficiency coefficient for higher/lower inlet pressure
//  double T_pe;     //Time constant for the torque development
//  int8 nstroke;    //Number of stroke
//  double m_f_cyc_max;  // Maximum amount of fuel injected per cycle (kg)
//  double C1;          // Heat loss coefficient
double const pi = 3.14159265359;

//Variables
double hu,su,uu,Ru,RFu,Rpu,RTu,uFu,upu,uTu,sFu,spu,sTu,Cpu,Cvu,Ku;
                    //Thermodynamic properties of inlet gas
double p_bar;       // pressure in bar
double m_cyc;       // mass of charge trapped per cycle
double n;           // number of revolution per second
double dmf;         // fuel burn rate (kg/s)
double Pe, Pe_d_nom;   // inst shaft power (W), delayed shaft power(W) 
double SFOC;        // Specific fuel oil consumption (g/kWh)
//code

GetThdynCombGasZachV1(*pu,*Tu,*Fu,fs[0],&Ru,&hu,&su,&uu,&RFu,&Rpu,&RTu,&uFu,&upu,
                    &uTu,&sFu,&spu,&sTu,&Cpu,&Cvu,&Ku);
p_bar = *pu/1.0e5;
if (p_bar > *p_a_inf){
    *vol_eff = p_bar*(p_bar*vol_eff_coeff1[0] + vol_eff_coeff1[1]) 
            + vol_eff_coeff1[2];
}
else {
    *vol_eff = p_bar*(p_bar*vol_eff_coeff2[0] + vol_eff_coeff2[1]) 
            + vol_eff_coeff2[2];
}
m_cyc = *vol_eff*(*Vd)*(*pu/(Ru*(*Tu)));
n = *omegae/(pi*(*nstroke));
*dmu = m_cyc*n;
*deu = *dmu*hu;
*dmbu = *dmu*(*Fu*(*fs))/(1 + *Fu*(*fs));

dmf = (*throttle)*(*m_f_cyc_max)*n;
Pe_d_nom = xC[0] / *Pe_nom;
SFOC = Pe_d_nom*(SFC[0]*Pe_d_nom + SFC[1]) + SFC[2];
Pe = 3.9e9*dmf/SFOC;

*dmd = *dmu + dmf;
*ded = *deu + *LHV*(1-*C1)*dmf - Pe;
*dmbd = *dmbu + dmf;
*Tqe = Pe / *omegae;
pe[0] = Pe_d_nom;
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  *  Derivatives function
  *
  */
void InCylinderMV_Derivatives_wrapper(const real_T *pu,
                          const real_T *Tu,
                          const real_T *Fu,
                          const real_T *pd,
                          const real_T *Td,
                          const real_T *Fd,
                          const real_T *omegae,
                          const real_T *throttle,
                          const real_T *dmu,
                          const real_T *deu,
                          const real_T *dmbu,
                          const real_T *dmd,
                          const real_T *ded,
                          const real_T *dmbd,
                          const real_T *Tqe,
                          const real_T *vol_eff,
                          real_T *dx ,
                          real_T *xC, 
                          const real_T  *fs,  const int_T  p_width0,
                          const real_T  *Vd,  const int_T  p_width1,
                          const real_T  *LHV,  const int_T  p_width2,
                          const real_T  *Pe_nom,  const int_T  p_width3,
                          const real_T  *SFC,  const int_T  p_width4,
                          const real_T  *vol_eff_coeff1,  const int_T  p_width5,
                          const real_T  *vol_eff_coeff2,  const int_T  p_width6,
                          const real_T  *T_pe,  const int_T  p_width7,
                          const real_T  *nstroke,  const int_T  p_width8,
                          const real_T  *m_f_cyc_max,  const int_T  p_width9,
                          const real_T  *C1,  const int_T  p_width10,
                          const real_T  *p_a_inf,  const int_T  p_width11,
                           const real_T *Pe0, const int_T  p_width12)
{
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_BEGIN --- EDIT HERE TO _END */
double n;           // number of revolution per second
double dmf;         // fuel burn rate (kg/s)
double Pe, Pe_d_nom;   // inst shaft power (W), delayed shaft power(W) 
double SFOC;        // Specific fuel oil consumption (g/kWh)
double const pi = 3.14159265359;

n = *omegae/(pi*(*nstroke));    
dmf = (*throttle)*(*m_f_cyc_max)*n;
Pe_d_nom = xC[0] / *Pe_nom;
SFOC = Pe_d_nom*(SFC[0]*Pe_d_nom + SFC[1]) + SFC[2];
Pe = 3.9e9*dmf/SFOC;
dx[0] = (Pe - xC[0])/ *T_pe;
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_END --- EDIT HERE TO _BEGIN */
}