/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Thu Aug  7 23:43:12 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void pCompCalc_Update_wrapper(const real_T *pCyl,
                          const real_T *vCyl,
                          const real_T *tempWall,
                          const real_T *exhVVOpen,
                          const real_T  *vComp,  const int_T p_width0,
                          real_T *pComp, real_T *reset)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
    const double coeffKappa[6] = {1.3714,0.0011656,2.9770e-08,1.2930e-05,
                                  2.4836e-09,-1.8433e-14};
                // coefficient for regression model for finding kappa
    const double corrFactKappaTw = 1.3464e-05; 
                // correction factor for kappa w.r.t. cylinder wall temp.
    double kappa;
    double compRatio;
    
    if ((exhVVOpen[0]>0)&(reset[0]==0)) {
        reset[0] = 1;
    }
    else {
        if ((exhVVOpen[0]==0)&(reset[0]==1)) {
            reset[0] = 0;
            compRatio = vCyl[0] / vComp[0];
            kappa = coeffKappa[0] + coeffKappa[1]*compRatio + 
                    coeffKappa[2]*pCyl[0]/1e5 + 
                    coeffKappa[3]*pow(compRatio,2) + 
                    coeffKappa[4]*compRatio*pCyl[0]/1e5 + 
                    coeffKappa[5]*pow(pCyl[0]/1e5,2);
            kappa = kappa + corrFactKappaTw*(900-tempWall[0]);
            pComp[0] = pCyl[0]*pow(vCyl[0]/vComp[0],kappa);
        }
    }
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
