/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Wed Aug  6 11:22:24 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>

/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void pMaxFinder_Update_wrapper(const real_T *t,
                          const real_T *phi,
                          const real_T *p,
                          real_T *lastTime,
                          int_T *newCycle,
                          real_T *tempPMax,
                          real_T *tempPhiAtPMax,
                          real_T *newPMax,
                          real_T *newPhiAtPMax)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
/* This sample sets the output equal to the input
      IMPLICIT NONE
      REAL*8 fi,p,pmax,newpmax,temppmax,fistart,fistop
      REAL*8 lastime,t,fipmax,tempfipmax,newfipmax
      LOGICAL new
      COMMON /pmaxpress/temppmax,newpmax,new,lastime,
     &     tempfipmax,newfipmax
      DATA temppmax/150.0e5/
      DATA new/.TRUE./
      DATA newpmax/150.0e5/
      DATA lastime/-1.0/

C -------------------------------------------------------------------

*/
double phi360, phiComb;
const double pi = 3.14159265359;

phi360 = phi[0]*180/pi;
phi360 = (((int)floor(phi360))%360) + (phi360 - floor(phi360));
if (phi360 > 180) {
    phiComb = phi360 - 360;
}
else {
    phiComb = phi360;
}
if (t[0] > lastTime[0]) {
    if ((phiComb>-10) & (phiComb<40) & (p[0] > 5.0e5)) {
        if (newCycle[0]) {
            newPMax[0] = tempPMax[0];
            newPhiAtPMax[0] = tempPhiAtPMax[0];
            tempPMax[0] = 0.0;
            newCycle[0] = 0;
        }
        if (p[0] > tempPMax[0]) {
            tempPMax[0] = p[0];
            tempPhiAtPMax[0] = phiComb;
        }
    }
    else {
        newCycle[0] = 1;
    }
    lastTime[0] = t[0];
}
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}
