/*
 * File: scavenging1Zone.c
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
* Created: Tue Sep  8 12:45:11 2015
*/
#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME scavenging1Zone
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS          9
/* Input Port  0 */
#define IN_PORT_0_NAME      pCyl
#define INPUT_0_WIDTH       1
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       real_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 1
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125
/* Input Port  1 */
#define IN_PORT_1_NAME      TCyl
#define INPUT_1_WIDTH       1
#define INPUT_DIMS_1_COL    1
#define INPUT_1_DTYPE       real_T
#define INPUT_1_COMPLEX     COMPLEX_NO
#define IN_1_FRAME_BASED    FRAME_NO
#define IN_1_BUS_BASED      0
#define IN_1_BUS_NAME       
#define IN_1_DIMS           1-D
#define INPUT_1_FEEDTHROUGH 1
#define IN_1_ISSIGNED        0
#define IN_1_WORDLENGTH      8
#define IN_1_FIXPOINTSCALING 1
#define IN_1_FRACTIONLENGTH  9
#define IN_1_BIAS            0
#define IN_1_SLOPE           0.125
/* Input Port  2 */
#define IN_PORT_2_NAME      FCyl
#define INPUT_2_WIDTH       1
#define INPUT_DIMS_2_COL    1
#define INPUT_2_DTYPE       real_T
#define INPUT_2_COMPLEX     COMPLEX_NO
#define IN_2_FRAME_BASED    FRAME_NO
#define IN_2_BUS_BASED      0
#define IN_2_BUS_NAME       
#define IN_2_DIMS           1-D
#define INPUT_2_FEEDTHROUGH 1
#define IN_2_ISSIGNED        0
#define IN_2_WORDLENGTH      8
#define IN_2_FIXPOINTSCALING 1
#define IN_2_FRACTIONLENGTH  9
#define IN_2_BIAS            0
#define IN_2_SLOPE           0.125
/* Input Port  3 */
#define IN_PORT_3_NAME      pIn
#define INPUT_3_WIDTH       1
#define INPUT_DIMS_3_COL    1
#define INPUT_3_DTYPE       real_T
#define INPUT_3_COMPLEX     COMPLEX_NO
#define IN_3_FRAME_BASED    FRAME_NO
#define IN_3_BUS_BASED      0
#define IN_3_BUS_NAME       
#define IN_3_DIMS           1-D
#define INPUT_3_FEEDTHROUGH 1
#define IN_3_ISSIGNED        0
#define IN_3_WORDLENGTH      8
#define IN_3_FIXPOINTSCALING 1
#define IN_3_FRACTIONLENGTH  9
#define IN_3_BIAS            0
#define IN_3_SLOPE           0.145
/* Input Port  4 */
#define IN_PORT_4_NAME      TIn
#define INPUT_4_WIDTH       1
#define INPUT_DIMS_4_COL    1
#define INPUT_4_DTYPE       real_T
#define INPUT_4_COMPLEX     COMPLEX_NO
#define IN_4_FRAME_BASED    FRAME_NO
#define IN_4_BUS_BASED      0
#define IN_4_BUS_NAME       
#define IN_4_DIMS           1-D
#define INPUT_4_FEEDTHROUGH 1
#define IN_4_ISSIGNED        0
#define IN_4_WORDLENGTH      8
#define IN_4_FIXPOINTSCALING 1
#define IN_4_FRACTIONLENGTH  9
#define IN_4_BIAS            0
#define IN_4_SLOPE           0.125
/* Input Port  5 */
#define IN_PORT_5_NAME      FIn
#define INPUT_5_WIDTH       1
#define INPUT_DIMS_5_COL    1
#define INPUT_5_DTYPE       real_T
#define INPUT_5_COMPLEX     COMPLEX_NO
#define IN_5_FRAME_BASED    FRAME_NO
#define IN_5_BUS_BASED      0
#define IN_5_BUS_NAME       
#define IN_5_DIMS           1-D
#define INPUT_5_FEEDTHROUGH 1
#define IN_5_ISSIGNED        0
#define IN_5_WORDLENGTH      8
#define IN_5_FIXPOINTSCALING 1
#define IN_5_FRACTIONLENGTH  9
#define IN_5_BIAS            0
#define IN_5_SLOPE           0.125
/* Input Port  6 */
#define IN_PORT_6_NAME      mDotIn
#define INPUT_6_WIDTH       1
#define INPUT_DIMS_6_COL    1
#define INPUT_6_DTYPE       real_T
#define INPUT_6_COMPLEX     COMPLEX_NO
#define IN_6_FRAME_BASED    FRAME_NO
#define IN_6_BUS_BASED      0
#define IN_6_BUS_NAME       
#define IN_6_DIMS           1-D
#define INPUT_6_FEEDTHROUGH 0
#define IN_6_ISSIGNED        0
#define IN_6_WORDLENGTH      8
#define IN_6_FIXPOINTSCALING 1
#define IN_6_FRACTIONLENGTH  9
#define IN_6_BIAS            0
#define IN_6_SLOPE           0.125
/* Input Port  7 */
#define IN_PORT_7_NAME      combState
#define INPUT_7_WIDTH       1
#define INPUT_DIMS_7_COL    1
#define INPUT_7_DTYPE       real_T
#define INPUT_7_COMPLEX     COMPLEX_NO
#define IN_7_FRAME_BASED    FRAME_NO
#define IN_7_BUS_BASED      0
#define IN_7_BUS_NAME       
#define IN_7_DIMS           1-D
#define INPUT_7_FEEDTHROUGH 1
#define IN_7_ISSIGNED        0
#define IN_7_WORDLENGTH      8
#define IN_7_FIXPOINTSCALING 1
#define IN_7_FRACTIONLENGTH  9
#define IN_7_BIAS            0
#define IN_7_SLOPE           0.125
/* Input Port  8 */
#define IN_PORT_8_NAME      phi
#define INPUT_8_WIDTH       1
#define INPUT_DIMS_8_COL    1
#define INPUT_8_DTYPE       real_T
#define INPUT_8_COMPLEX     COMPLEX_NO
#define IN_8_FRAME_BASED    FRAME_NO
#define IN_8_BUS_BASED      0
#define IN_8_BUS_NAME       
#define IN_8_DIMS           1-D
#define INPUT_8_FEEDTHROUGH 1
#define IN_8_ISSIGNED        0
#define IN_8_WORDLENGTH      8
#define IN_8_FIXPOINTSCALING 1
#define IN_8_FRACTIONLENGTH  9
#define IN_8_BIAS            0
#define IN_8_SLOPE           0.125

#define NUM_OUTPUTS          4
/* Output Port  0 */
#define OUT_PORT_0_NAME      TOut
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125

/* Output Port  1 */
#define OUT_PORT_1_NAME      FOut
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       real_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125

/* Output Port  2 */
#define OUT_PORT_2_NAME      lambS
#define OUTPUT_2_WIDTH       1
#define OUTPUT_DIMS_2_COL    1
#define OUTPUT_2_DTYPE       real_T
#define OUTPUT_2_COMPLEX     COMPLEX_NO
#define OUT_2_FRAME_BASED    FRAME_NO
#define OUT_2_BUS_BASED      0
#define OUT_2_BUS_NAME       
#define OUT_2_DIMS           1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            1
#define OUT_2_SLOPE           0.125

/* Output Port  3 */
#define OUT_PORT_3_NAME      beta
#define OUTPUT_3_WIDTH       1
#define OUTPUT_DIMS_3_COL    1
#define OUTPUT_3_DTYPE       real_T
#define OUTPUT_3_COMPLEX     COMPLEX_NO
#define OUT_3_FRAME_BASED    FRAME_NO
#define OUT_3_BUS_BASED      0
#define OUT_3_BUS_NAME       
#define OUT_3_DIMS           1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125


#define NPARAMS              5
/* Parameter  1 */
#define PARAMETER_0_NAME      kai
#define PARAMETER_0_DTYPE     real_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO
/* Parameter  2 */
#define PARAMETER_1_NAME      delta
#define PARAMETER_1_DTYPE     real_T
#define PARAMETER_1_COMPLEX   COMPLEX_NO
/* Parameter  3 */
#define PARAMETER_2_NAME      fs
#define PARAMETER_2_DTYPE     real_T
#define PARAMETER_2_COMPLEX   COMPLEX_NO
/* Parameter  4 */
#define PARAMETER_3_NAME      volDisp
#define PARAMETER_3_DTYPE     real_T
#define PARAMETER_3_COMPLEX   COMPLEX_NO
/* Parameter  5 */
#define PARAMETER_4_NAME      CAIPO
#define PARAMETER_4_DTYPE     real_T
#define PARAMETER_4_COMPLEX   COMPLEX_NO

#define NDWORKS              7
// DWork 1
#define DWORK_0_NAME         resetIn
#define DWORK_0_WIDTH        1
#define DWORK_0_DTYPE        int_T
#define DWORK_0_COMPLEX      COMPLEX_NO
// DWork 2
#define DWORK_1_NAME         resetOut
#define DWORK_1_WIDTH        1
#define DWORK_1_DTYPE        int_T
#define DWORK_1_COMPLEX      COMPLEX_NO
// DWork 3
#define DWORK_2_NAME         mInPrev
#define DWORK_2_WIDTH        1
#define DWORK_2_DTYPE        real_T
#define DWORK_2_COMPLEX      COMPLEX_NO
// DWork 4
#define DWORK_3_NAME         F0
#define DWORK_3_WIDTH        1
#define DWORK_3_DTYPE        real_T
#define DWORK_3_COMPLEX      COMPLEX_NO
// DWork 5
#define DWORK_4_NAME         rho0
#define DWORK_4_WIDTH        1
#define DWORK_4_DTYPE        real_T
#define DWORK_4_COMPLEX      COMPLEX_NO
// DWork 6
#define DWORK_5_NAME         hIn0
#define DWORK_5_WIDTH        1
#define DWORK_5_DTYPE        real_T
#define DWORK_5_COMPLEX      COMPLEX_NO
// DWork 7
#define DWORK_6_NAME         hCyl0
#define DWORK_6_WIDTH        1
#define DWORK_6_DTYPE        real_T
#define DWORK_6_COMPLEX      COMPLEX_NO


#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      1
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__GetThdynCombGasZachV1.c"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S) ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S) ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S) ssGetSFcnParam(S, 4)

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

extern void scavenging1Zone_Outputs_wrapper(const real_T *pCyl,
			const real_T *TCyl,
			const real_T *FCyl,
			const real_T *pIn,
			const real_T *TIn,
			const real_T *FIn,
			const real_T *combState, 
			const real_T *phi,
			real_T *TOut,
			real_T *FOut,
			real_T *lambS,
			real_T *betaS,
			const real_T *xC,
			const real_T  *kai, const int_T  p_width0,
			const real_T  *delta, const int_T  p_width1,
			const real_T  *fs, const int_T  p_width2,
			const real_T  *volDisp, const int_T  p_width3,
			const real_T  *CAIPO, const int_T  p_width4,
            const int_T *resetIn, 
            const int_T *resetOut, 
            const real_T *mInPrev,
            const real_T *F0,
			const real_T *rho0,
			const real_T *hIn0,
			const real_T *hCyl0);
extern void scavenging1Zone_Derivatives_wrapper(const real_T *pCyl,
			const real_T *TCyl,
			const real_T *FCyl,
			const real_T *pIn,
			const real_T *TIn,
			const real_T *FIn,
			const real_T *mDotIn,
			const real_T *combState,
			const real_T *phi,
			const real_T *TOut,
			const real_T *FOut,
			real_T *dx,
			real_T *xC,
			const real_T  *kai,  const int_T  p_width0,
			const real_T  *delta,  const int_T  p_width1,
			const real_T  *fs,  const int_T  p_width2,
			const real_T  *volDisp,  const int_T  p_width3,
			const real_T  *CAIPO, const int_T  p_width4);

extern void scavenging1Zone_Update_wrapper(const real_T *pCyl,
			const real_T *TCyl,
			const real_T *FCyl,
			const real_T *pIn,
			const real_T *TIn,
			const real_T *FIn,
			const real_T *mDotIn,
			const real_T *combState,
			const real_T *phi,
			const real_T *TOut,
			const real_T *FOut,
			real_T *dx,
			real_T *xC,
			const real_T  *kai,  const int_T  p_width0,
			const real_T  *delta,  const int_T  p_width1,
			const real_T  *fs,  const int_T  p_width2,
			const real_T  *volDisp,  const int_T  p_width3,
			const real_T  *CAIPO, const int_T  p_width4,
            int_T *resetIn,
			int_T *resetOut,
            real_T *mInPrev,
            real_T *F0,
			real_T *rho0,			
			real_T *hIn0,
			real_T *hCyl0);

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
 #if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
   /* Function: mdlCheckParameters =============================================
     * Abstract:
     *    Validate our parameters to verify they are okay.
     */
    static void mdlCheckParameters(SimStruct *S)
    {
     int paramIndex  = 0;
     bool validParam = false;
     /* All parameters must match the S-function Builder Dialog */
     

	 {
	  const mxArray *pVal0 = ssGetSFcnParam(S,0);
	  if (!IS_PARAM_DOUBLE(pVal0)) {
	    validParam = true;
	    paramIndex = 0;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal1 = ssGetSFcnParam(S,1);
	  if (!IS_PARAM_DOUBLE(pVal1)) {
	    validParam = true;
	    paramIndex = 1;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal2 = ssGetSFcnParam(S,2);
	  if (!IS_PARAM_DOUBLE(pVal2)) {
	    validParam = true;
	    paramIndex = 2;
	    goto EXIT_POINT;
	  }
	 }

	 {
	  const mxArray *pVal3 = ssGetSFcnParam(S,3);
	  if (!IS_PARAM_DOUBLE(pVal3)) {
	    validParam = true;
	    paramIndex = 3;
	    goto EXIT_POINT;
	  }
	 }

	{
		const mxArray *pVal4 = ssGetSFcnParam(S, 4);
		if (!IS_PARAM_DOUBLE(pVal4)) {
			validParam = true;
			paramIndex = 4;
			goto EXIT_POINT;
		}
	}

     EXIT_POINT:
      if (validParam) {
          char parameterErrorMsg[1024];
          sprintf(parameterErrorMsg, "The data type and or complexity of parameter  %d does not match the "
                  "information specified in the S-function Builder dialog. "
                  "For non-double parameters you will need to cast them using int8, int16, "
                  "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
	  ssSetErrorStatus(S,parameterErrorMsg);
      }
	return;
    }
 #endif /* MDL_CHECK_PARAMETERS */
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);  /* Number of expected parameters */
      #if defined(MATLAB_MEX_FILE)
	if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
	  mdlCheckParameters(S);
	  if (ssGetErrorStatus(S) != NULL) {
	    return;
	  }
	 } else {
	   return; /* Parameter mismatch will be reported by Simulink */
	 }
      #endif
	ssSetSimStateCompliance(S, USE_DEFAULT_SIM_STATE);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /*Input Port 0 */
    ssSetInputPortWidth(S,  0, INPUT_0_WIDTH); /* */
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /*Input Port 1 */
    ssSetInputPortWidth(S,  1, INPUT_1_WIDTH); /* */
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /*Input Port 2 */
    ssSetInputPortWidth(S,  2, INPUT_2_WIDTH); /* */
    ssSetInputPortDataType(S, 2, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/

    /*Input Port 3 */
    ssSetInputPortWidth(S,  3, INPUT_3_WIDTH); /* */
    ssSetInputPortDataType(S, 3, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1); /*direct input signal access*/

    /*Input Port 4 */
    ssSetInputPortWidth(S,  4, INPUT_4_WIDTH); /* */
    ssSetInputPortDataType(S, 4, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1); /*direct input signal access*/

    /*Input Port 5 */
    ssSetInputPortWidth(S,  5, INPUT_5_WIDTH); /* */
    ssSetInputPortDataType(S, 5, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1); /*direct input signal access*/

    /*Input Port 6 */
    ssSetInputPortWidth(S,  6, INPUT_6_WIDTH); /* */
    ssSetInputPortDataType(S, 6, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  6, INPUT_6_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 6, 1); /*direct input signal access*/

    /*Input Port 7 */
    ssSetInputPortWidth(S,  7, INPUT_7_WIDTH); /* */
    ssSetInputPortDataType(S, 7, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  7, INPUT_7_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 7, 1); /*direct input signal access*/

    /*Input Port 8 */
    ssSetInputPortWidth(S,  8, INPUT_8_WIDTH); /* */
    ssSetInputPortDataType(S, 8, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  8, INPUT_8_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 8, INPUT_8_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 8, 1); /*direct input signal access*/

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);

	ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
	ssSetOutputPortDataType(S, 1, SS_DOUBLE);
	ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);

	ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
	ssSetOutputPortDataType(S, 2, SS_DOUBLE);
	ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);

	ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
	ssSetOutputPortDataType(S, 3, SS_DOUBLE);
	ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetNumDWork(S,NDWORKS);
    /*DWork vector 1*/
    ssSetDWorkWidth(S, 0, DWORK_0_WIDTH);
    ssSetDWorkDataType(S, 0, SS_INTEGER);
    /*DWork vector 2*/
    ssSetDWorkWidth(S, 1, DWORK_1_WIDTH);
    ssSetDWorkDataType(S, 1, SS_INTEGER);
    /*DWork vector 3*/
    ssSetDWorkWidth(S, 2, DWORK_2_WIDTH);
    ssSetDWorkDataType(S, 2, SS_DOUBLE);
    /*DWork vector 4*/
    ssSetDWorkWidth(S, 3, DWORK_3_WIDTH);
    ssSetDWorkDataType(S, 3, SS_DOUBLE);
	/*DWork vector 5*/
	ssSetDWorkWidth(S, 4, DWORK_4_WIDTH);
	ssSetDWorkDataType(S, 4, SS_DOUBLE);
	/*DWork vector 6*/
	ssSetDWorkWidth(S, 5, DWORK_4_WIDTH);
	ssSetDWorkDataType(S, 5, SS_DOUBLE);
	/*DWork vector 7*/
	ssSetDWorkWidth(S, 6, DWORK_4_WIDTH);
	ssSetDWorkDataType(S, 6, SS_DOUBLE);


    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR | 
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}
#define MDL_INITIALIZE_CONDITIONS
 /* Function: mdlInitializeConditions ========================================
  * Abstract:
  *    Initialize the states
  */
 static void mdlInitializeConditions(SimStruct *S)
 {
   
   real_T *xC   = ssGetContStates(S);
   int_T *resetIn = (int_T *) ssGetDWork(S,0);
   int_T *resetOut = (int_T *) ssGetDWork(S,1);
   real_T *mInPrev = (real_T *) ssGetDWork(S,2);
   real_T *F0 = (real_T *) ssGetDWork(S,3);
   real_T *rho0 = (real_T *)ssGetDWork(S, 4);
   real_T *hIn0 = (real_T *)ssGetDWork(S, 5);
   real_T *hCyl0 = (real_T *)ssGetDWork(S, 6);

    /* Initialize the dwork*/
   resetIn[0] = 1;
   resetOut[0] = 1;
   mInPrev[0] = 0;
   F0[0] = 0;
   rho0[0] = 1.16;
   hIn0[0] = 3e5;
   hCyl0[0] = 3e5;

    xC[0] =  0;
 }
#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/*
#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{

     const char_T *rtParamNames[] = {"P1","P2","P3","P4"};
     ssRegAllTunableParamsAsRunTimeParams(S, rtParamNames);
}

#endif
*/
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
	const real_T   *pCyl = (const real_T*)ssGetInputPortSignal(S, 0);
	const real_T   *TCyl = (const real_T*)ssGetInputPortSignal(S, 1);
    const real_T   *FCyl  = (const real_T*) ssGetInputPortSignal(S,2);
    const real_T   *pIn  = (const real_T*) ssGetInputPortSignal(S,3);
    const real_T   *TIn  = (const real_T*) ssGetInputPortSignal(S,4);
    const real_T   *FIn  = (const real_T*) ssGetInputPortSignal(S,5);
    const real_T   *combState  = (const real_T*) ssGetInputPortSignal(S,7);
    const real_T   *phi  = (const real_T*) ssGetInputPortSignal(S,8);
	real_T        *TOut = (real_T *)ssGetOutputPortRealSignal(S, 0);
    real_T        *FOut  = (real_T *)ssGetOutputPortRealSignal(S,1);
	real_T		  *lambS = (real_T *)ssGetOutputPortRealSignal(S,2);
	real_T		  *betaS = (real_T *)ssGetOutputPortRealSignal(S, 3);
    const real_T   *xC = ssGetContStates(S);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
	const int_T   p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
    const real_T  *kai  = (const real_T *)mxGetData(PARAM_DEF0(S));
    const real_T  *delta  = (const real_T *)mxGetData(PARAM_DEF1(S));
    const real_T  *fs  = (const real_T *)mxGetData(PARAM_DEF2(S));
    const real_T  *volDisp  = (const real_T *)mxGetData(PARAM_DEF3(S));
	const real_T  *CAIPO = (const real_T *)mxGetData(PARAM_DEF4(S));
    const int_T *resetIn = (const int_T *) ssGetDWork(S,0);
    const int_T *resetOut = (const int_T *) ssGetDWork(S,1);
    const real_T *mInPrev = (const real_T *) ssGetDWork(S,2);
    const real_T *F0 = (const real_T *) ssGetDWork(S,3);
	const real_T *rho0 = (const real_T *)ssGetDWork(S,4);
	const real_T *hIn0 = (const real_T *)ssGetDWork(S, 5);
	const real_T *hCyl0 = (const real_T *)ssGetDWork(S, 6);


	scavenging1Zone_Outputs_wrapper(pCyl,TCyl,FCyl,pIn,TIn,FIn,combState,phi,
		TOut,FOut,lambS,betaS, xC, 
		kai,p_width0,delta,p_width1,fs,p_width2,volDisp,p_width3,CAIPO,p_width4,
		resetIn,resetOut,mInPrev,F0,rho0,hIn0,hCyl0);
}

#define MDL_DERIVATIVES  /* Change to #undef to remove function */
/* Function: mdlDerivatives =================================================
   * Abstract:
   *    In this function, you compute the S-function block's derivatives.
   *    The derivatives are placed in the derivative vector, ssGetdX(S).
   */
  static void mdlDerivatives(SimStruct *S)
  {
	const real_T   *pCyl = (const real_T*)ssGetInputPortSignal(S, 0);
	const real_T   *TCyl = (const real_T*)ssGetInputPortSignal(S, 1);
    const real_T   *FCyl  = (const real_T*) ssGetInputPortSignal(S,2);
    const real_T   *pIn  = (const real_T*) ssGetInputPortSignal(S,3);
    const real_T   *TIn  = (const real_T*) ssGetInputPortSignal(S,4);
    const real_T   *FIn  = (const real_T*) ssGetInputPortSignal(S,5);
    const real_T   *mDotIn  = (const real_T*) ssGetInputPortSignal(S,6);
    const real_T   *combState  = (const real_T*) ssGetInputPortSignal(S,7);
    const real_T   *phi  = (const real_T*) ssGetInputPortSignal(S,8);
    real_T         *dx  = ssGetdX(S);
    real_T         *xC  = ssGetContStates(S);
	const real_T   *TOut = (real_T *)ssGetOutputPortRealSignal(S, 0);
    const real_T   *FOut  = (real_T *) ssGetOutputPortRealSignal(S,1);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
	const int_T   p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
    const real_T  *kai  = (const real_T *)mxGetData(PARAM_DEF0(S));
    const real_T  *delta  = (const real_T *)mxGetData(PARAM_DEF1(S));
    const real_T  *fs  = (const real_T *)mxGetData(PARAM_DEF2(S));
    const real_T  *volDisp  = (const real_T *)mxGetData(PARAM_DEF3(S));
	const real_T  *CAIPO = (const real_T *)mxGetData(PARAM_DEF3(S));

	scavenging1Zone_Derivatives_wrapper(pCyl,TCyl,FCyl,pIn,TIn,FIn,mDotIn,combState,phi,
		TOut,FOut, dx, xC,
		kai,p_width0,delta,p_width1,fs,p_width2,volDisp,p_width3,CAIPO,p_width4);

}

#define MDL_UPDATE  /* Change to #undef to remove function */
/* Function: mdlUpdate ======================================================
   * Abstract:
   *    This function is called once for every major integration time step.
   *    Discrete states are typically updated here, but this function is useful
   *    for performing any tasks that should only take place once per
   *    integration step.
   */
  static void mdlUpdate(SimStruct *S, int_T tid)
  {
	const real_T   *pCyl = (const real_T*)ssGetInputPortSignal(S, 0);
	const real_T   *TCyl = (const real_T*)ssGetInputPortSignal(S, 1);
    const real_T   *FCyl  = (const real_T*) ssGetInputPortSignal(S,2);
    const real_T   *pIn  = (const real_T*) ssGetInputPortSignal(S,3);
    const real_T   *TIn  = (const real_T*) ssGetInputPortSignal(S,4);
    const real_T   *FIn  = (const real_T*) ssGetInputPortSignal(S,5);
    const real_T   *mDotIn  = (const real_T*) ssGetInputPortSignal(S,6);
    const real_T   *combState  = (const real_T*) ssGetInputPortSignal(S,7);
    const real_T   *phi  = (const real_T*) ssGetInputPortSignal(S,8);
    real_T         *dx  = ssGetdX(S);
    real_T         *xC  = ssGetContStates(S);
	real_T		  *TOut = (real_T *)ssGetOutputPortRealSignal(S, 0);
    real_T        *FOut  = (real_T *) ssGetOutputPortRealSignal(S,1);
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
	const int_T   p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
    const real_T  *kai  = (const real_T *)mxGetData(PARAM_DEF0(S));
    const real_T  *delta  = (const real_T *)mxGetData(PARAM_DEF1(S));
    const real_T  *fs  = (const real_T *)mxGetData(PARAM_DEF2(S));
    const real_T  *volDisp  = (const real_T *)mxGetData(PARAM_DEF3(S));
	const real_T  *CAIPO = (const real_T *)mxGetData(PARAM_DEF4(S));
    int_T *resetIn = (int_T *) ssGetDWork(S,0);
    int_T *resetOut = (int_T *) ssGetDWork(S,1);
    real_T *mInPrev = (real_T *) ssGetDWork(S,2);
    real_T *F0 = (real_T *) ssGetDWork(S,3);
	real_T *rho0 = (real_T *)ssGetDWork(S,4);
	real_T *hIn0 = (real_T *)ssGetDWork(S, 5);
	real_T *hCyl0 = (real_T *)ssGetDWork(S, 6);

	scavenging1Zone_Update_wrapper(pCyl,TCyl,FCyl,pIn,TIn,FIn,mDotIn,combState,phi,
		TOut,FOut, dx, xC,
		kai,p_width0,delta,p_width1,fs,p_width2,volDisp,p_width3,CAIPO,p_width4,
		resetIn,resetOut,mInPrev,F0,rho0,hIn0,hCyl0);
}

  
/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{



}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


