/*
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is a wrapper S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_wrapper_XXXXX_Changes_BEGIN 
  *            Your Changes go here
  *        %%%-SFUNWIZ_wrapper_XXXXXX_Changes_END
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder User's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *   Created: Sat Dec 13 10:57:16 2014
  */


/*
 * Include Files
 *
 */
#if defined(MATLAB_MEX_FILE)
#include "tmwtypes.h"
#include "simstruc_types.h"
#else
#include "rtwtypes.h"
#endif

/* %%%-SFUNWIZ_wrapper_includes_Changes_BEGIN --- EDIT HERE TO _END */
#include <math.h>
/* %%%-SFUNWIZ_wrapper_includes_Changes_END --- EDIT HERE TO _BEGIN */
#define u_width 1
#define y_width 1
/*
 * Create external references here.  
 *
 */
/* %%%-SFUNWIZ_wrapper_externs_Changes_BEGIN --- EDIT HERE TO _END */
/* extern double func(double a); */
/* %%%-SFUNWIZ_wrapper_externs_Changes_END --- EDIT HERE TO _BEGIN */

/*
 * Output functions
 *
 */
void SpeedController_Outputs_wrapper(const real_T *SP,
                          const real_T *MV,
                          real_T *u ,
			   const real_T *xC,
                          const real_T  *Kp, const int_T  p_width0, 
                          const real_T  *Td, const int_T  p_width1, 
                          const real_T  *N, const int_T  p_width2, 
                          const real_T  *Ti, const int_T  p_width3, 
                          const real_T  *Kb, const int_T  p_width4, 
                          const real_T  *uMax, const int_T  p_width5, 
                          const real_T  *uMin, const int_T  p_width6, 
                          const real_T  *u0, const int_T p_width7)
{
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_BEGIN --- EDIT HERE TO _END */
double err;
double uP, uD, uI;
double uGov; 
err = SP[0] - MV[0];
uP = Kp[0] * err;
uD = uP * N[0] - xC[1];
uI = xC[0];
uGov = uP + uI + uD;
u[0] = (uGov < uMin[0]) ? 
		/* minimum */
		uMin[0]
	:
		/* if (uP + uI) + uD > maximum...  */
		((uGov > uMax[0]) ? 
			/* maximum */
			uMax[0]
		:
			/* (uP + uI) + uD */
			uGov
		)
	;
/* %%%-SFUNWIZ_wrapper_Outputs_Changes_END --- EDIT HERE TO _BEGIN */
}

/*
  *  Derivatives function
  *
  */
void SpeedController_Derivatives_wrapper(const real_T *SP,
                          const real_T *MV,
                          const real_T *uSat,
                          const real_T *u,
                          real_T *dx ,
                          real_T *xC, 
                          const real_T  *Kp,  const int_T  p_width0,
                          const real_T  *Td,  const int_T  p_width1,
                          const real_T  *N,  const int_T  p_width2,
                          const real_T  *Ti,  const int_T  p_width3,
                          const real_T  *Kb,  const int_T  p_width4,
                          const real_T  *uMax,  const int_T  p_width5,
                          const real_T  *uMin,  const int_T  p_width6,
                           const real_T *u0, const int_T  p_width7)
{
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_BEGIN --- EDIT HERE TO _END */
double err;
double uP, uD, uI;
double uGov; 
err = SP[0] - MV[0];
uP = Kp[0] * err;
uD = uP * N[0] - xC[1];
uI = xC[0];
uGov = uP + uI + uD;

dx[0] = ((err + Kb[0]*(uSat[0] - uGov)) * Kp[0]) / Ti[0];
dx[1] = uD*N[0] / Td[0];
/* %%%-SFUNWIZ_wrapper_Derivatives_Changes_END --- EDIT HERE TO _BEGIN */
}