/*
 * File: ThdynCV.c
 *
 *
  *
  *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
  *
  *   This file is an S-function produced by the S-Function
  *   Builder which only recognizes certain fields.  Changes made
  *   outside these fields will be lost the next time the block is
  *   used to load, edit, and resave this file. This file will be overwritten
  *   by the S-function Builder block. If you want to edit this file by hand, 
  *   you must change it only in the area defined as:  
  *
  *        %%%-SFUNWIZ_defines_Changes_BEGIN
  *        #define NAME 'replacement text' 
  *        %%% SFUNWIZ_defines_Changes_END
  *
  *   DO NOT change NAME--Change the 'replacement text' only.
  *
  *   For better compatibility with the Simulink Coder, the
  *   "wrapper" S-function technique is used.  This is discussed
  *   in the Simulink Coder's Manual in the Chapter titled,
  *   "Wrapper S-functions".
  *
  *  -------------------------------------------------------------------------
  * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
  *  ------------------------------------------------------------------------- 
 * Created: Tue Aug  5 16:32:52 2014
 * 
 *
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME ThdynCVNV2Zone
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */

#define NUM_INPUTS          10
/* Input Port  0 */
#define IN_PORT_0_NAME      dm
#define INPUT_0_WIDTH       1
#define INPUT_DIMS_0_COL    1
#define INPUT_0_DTYPE       real_T
#define INPUT_0_COMPLEX     COMPLEX_NO
#define IN_0_FRAME_BASED    FRAME_NO
#define IN_0_BUS_BASED      0
#define IN_0_BUS_NAME       
#define IN_0_DIMS           1-D
#define INPUT_0_FEEDTHROUGH 0
#define IN_0_ISSIGNED        0
#define IN_0_WORDLENGTH      8
#define IN_0_FIXPOINTSCALING 1
#define IN_0_FRACTIONLENGTH  9
#define IN_0_BIAS            0
#define IN_0_SLOPE           0.125
/* Input Port  1 */
#define IN_PORT_1_NAME      dmb
#define INPUT_1_WIDTH       1
#define INPUT_DIMS_1_COL    1
#define INPUT_1_DTYPE       real_T
#define INPUT_1_COMPLEX     COMPLEX_NO
#define IN_1_FRAME_BASED    FRAME_NO
#define IN_1_BUS_BASED      0
#define IN_1_BUS_NAME       
#define IN_1_DIMS           1-D
#define INPUT_1_FEEDTHROUGH 0
#define IN_1_ISSIGNED        0
#define IN_1_WORDLENGTH      8
#define IN_1_FIXPOINTSCALING 1
#define IN_1_FRACTIONLENGTH  9
#define IN_1_BIAS            0
#define IN_1_SLOPE           0.125
/* Input Port  2 */
#define IN_PORT_2_NAME      dV
#define INPUT_2_WIDTH       1
#define INPUT_DIMS_2_COL    1
#define INPUT_2_DTYPE       real_T
#define INPUT_2_COMPLEX     COMPLEX_NO
#define IN_2_FRAME_BASED    FRAME_NO
#define IN_2_BUS_BASED      0
#define IN_2_BUS_NAME       
#define IN_2_DIMS           1-D
#define INPUT_2_FEEDTHROUGH 0
#define IN_2_ISSIGNED        0
#define IN_2_WORDLENGTH      8
#define IN_2_FIXPOINTSCALING 1
#define IN_2_FRACTIONLENGTH  9
#define IN_2_BIAS            0
#define IN_2_SLOPE           0.125
/* Input Port  3 */
#define IN_PORT_3_NAME      dmfb
#define INPUT_3_WIDTH       1
#define INPUT_DIMS_3_COL    1
#define INPUT_3_DTYPE       real_T
#define INPUT_3_COMPLEX     COMPLEX_NO
#define IN_3_FRAME_BASED    FRAME_NO
#define IN_3_BUS_BASED      0
#define IN_3_BUS_NAME       
#define IN_3_DIMS           1-D
#define INPUT_3_FEEDTHROUGH 0
#define IN_3_ISSIGNED        0
#define IN_3_WORDLENGTH      8
#define IN_3_FIXPOINTSCALING 1
#define IN_3_FRACTIONLENGTH  9
#define IN_3_BIAS            0
#define IN_3_SLOPE           0.125
/* Input Port  4 */
#define IN_PORT_4_NAME      dQCyl
#define INPUT_4_WIDTH       1
#define INPUT_DIMS_4_COL    1
#define INPUT_4_DTYPE       real_T
#define INPUT_4_COMPLEX     COMPLEX_NO
#define IN_4_FRAME_BASED    FRAME_NO
#define IN_4_BUS_BASED      0
#define IN_4_BUS_NAME       
#define IN_4_DIMS           1-D
#define INPUT_4_FEEDTHROUGH 0
#define IN_4_ISSIGNED        0
#define IN_4_WORDLENGTH      8
#define IN_4_FIXPOINTSCALING 1
#define IN_4_FRACTIONLENGTH  9
#define IN_4_BIAS            0
#define IN_4_SLOPE           0.125
/* Input Port  5 */
#define IN_PORT_5_NAME      dHCyl
#define INPUT_5_WIDTH       1
#define INPUT_DIMS_5_COL    1
#define INPUT_5_DTYPE       real_T
#define INPUT_5_COMPLEX     COMPLEX_NO
#define IN_5_FRAME_BASED    FRAME_NO
#define IN_5_BUS_BASED      0
#define IN_5_BUS_NAME       
#define IN_5_DIMS           1-D
#define INPUT_5_FEEDTHROUGH 0
#define IN_5_ISSIGNED        0
#define IN_5_WORDLENGTH      8
#define IN_5_FIXPOINTSCALING 1
#define IN_5_FRACTIONLENGTH  9
#define IN_5_BIAS            0
#define IN_5_SLOPE           0.125
/* Input Port  6 */
#define IN_PORT_6_NAME      dWCyl
#define INPUT_6_WIDTH       1
#define INPUT_DIMS_6_COL    1
#define INPUT_6_DTYPE       real_T
#define INPUT_6_COMPLEX     COMPLEX_NO
#define IN_6_FRAME_BASED    FRAME_NO
#define IN_6_BUS_BASED      0
#define IN_6_BUS_NAME       
#define IN_6_DIMS           1-D
#define INPUT_6_FEEDTHROUGH 0
#define IN_6_ISSIGNED        0
#define IN_6_WORDLENGTH      8
#define IN_6_FIXPOINTSCALING 1
#define IN_6_FRACTIONLENGTH  9
#define IN_6_BIAS            0
#define IN_6_SLOPE           0.125
/* Input Port  7 */
#define IN_PORT_7_NAME      FComb
#define INPUT_7_WIDTH       1
#define INPUT_DIMS_7_COL    1
#define INPUT_7_DTYPE       real_T
#define INPUT_7_COMPLEX     COMPLEX_NO
#define IN_7_FRAME_BASED    FRAME_NO
#define IN_7_BUS_BASED      0
#define IN_7_BUS_NAME       
#define IN_7_DIMS           1-D
#define INPUT_7_FEEDTHROUGH 1
#define IN_7_ISSIGNED        0
#define IN_7_WORDLENGTH      8
#define IN_7_FIXPOINTSCALING 1
#define IN_7_FRACTIONLENGTH  9
#define IN_7_BIAS            0
#define IN_7_SLOPE           0.125
/* Input Port  8 */
#define IN_PORT_8_NAME      phi
#define INPUT_8_WIDTH       1
#define INPUT_DIMS_8_COL    1
#define INPUT_8_DTYPE       real_T
#define INPUT_8_COMPLEX     COMPLEX_NO
#define IN_8_FRAME_BASED    FRAME_NO
#define IN_8_BUS_BASED      0
#define IN_8_BUS_NAME       
#define IN_8_DIMS           1-D
#define INPUT_8_FEEDTHROUGH 1
#define IN_8_ISSIGNED        0
#define IN_8_WORDLENGTH      8
#define IN_8_FIXPOINTSCALING 1
#define IN_8_FRACTIONLENGTH  9
#define IN_8_BIAS            0
#define IN_8_SLOPE           0.125
/* Input Port  9 */
#define IN_PORT_9_NAME      combState
#define INPUT_9_WIDTH       1
#define INPUT_DIMS_9_COL    1
#define INPUT_9_DTYPE       real_T
#define INPUT_9_COMPLEX     COMPLEX_NO
#define IN_9_FRAME_BASED    FRAME_NO
#define IN_9_BUS_BASED      0
#define IN_9_BUS_NAME       
#define IN_9_DIMS           1-D
#define INPUT_9_FEEDTHROUGH 0
#define IN_9_ISSIGNED        0
#define IN_9_WORDLENGTH      8
#define IN_9_FIXPOINTSCALING 1
#define IN_9_FRACTIONLENGTH  9
#define IN_9_BIAS            0
#define IN_9_SLOPE           0.125

#define NUM_OUTPUTS          8
/* Output Port  0 */
#define OUT_PORT_0_NAME      pu
#define OUTPUT_0_WIDTH       1
#define OUTPUT_DIMS_0_COL    1
#define OUTPUT_0_DTYPE       real_T
#define OUTPUT_0_COMPLEX     COMPLEX_NO
#define OUT_0_FRAME_BASED    FRAME_NO
#define OUT_0_BUS_BASED      0
#define OUT_0_BUS_NAME       
#define OUT_0_DIMS           1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME      Tu
#define OUTPUT_1_WIDTH       1
#define OUTPUT_DIMS_1_COL    1
#define OUTPUT_1_DTYPE       real_T
#define OUTPUT_1_COMPLEX     COMPLEX_NO
#define OUT_1_FRAME_BASED    FRAME_NO
#define OUT_1_BUS_BASED      0
#define OUT_1_BUS_NAME       
#define OUT_1_DIMS           1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME      Fu
#define OUTPUT_2_WIDTH       1
#define OUTPUT_DIMS_2_COL    1
#define OUTPUT_2_DTYPE       real_T
#define OUTPUT_2_COMPLEX     COMPLEX_NO
#define OUT_2_FRAME_BASED    FRAME_NO
#define OUT_2_BUS_BASED      0
#define OUT_2_BUS_NAME       
#define OUT_2_DIMS           1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125
/* Output Port  3 */
#define OUT_PORT_3_NAME      Vu
#define OUTPUT_3_WIDTH       1
#define OUTPUT_DIMS_3_COL    1
#define OUTPUT_3_DTYPE       real_T
#define OUTPUT_3_COMPLEX     COMPLEX_NO
#define OUT_3_FRAME_BASED    FRAME_NO
#define OUT_3_BUS_BASED      0
#define OUT_3_BUS_NAME       
#define OUT_3_DIMS           1-D
#define OUT_3_ISSIGNED        1
#define OUT_3_WORDLENGTH      8
#define OUT_3_FIXPOINTSCALING 1
#define OUT_3_FRACTIONLENGTH  3
#define OUT_3_BIAS            0
#define OUT_3_SLOPE           0.125
/* Output Port  4 */
#define OUT_PORT_4_NAME      Tb
#define OUTPUT_4_WIDTH       1
#define OUTPUT_DIMS_4_COL    1
#define OUTPUT_4_DTYPE       real_T
#define OUTPUT_4_COMPLEX     COMPLEX_NO
#define OUT_4_FRAME_BASED    FRAME_NO
#define OUT_4_BUS_BASED      0
#define OUT_4_BUS_NAME       
#define OUT_4_DIMS           1-D
#define OUT_4_ISSIGNED        1
#define OUT_4_WORDLENGTH      8
#define OUT_4_FIXPOINTSCALING 1
#define OUT_4_FRACTIONLENGTH  3
#define OUT_4_BIAS            0
#define OUT_4_SLOPE           0.125
/* Output Port  5 */
#define OUT_PORT_5_NAME      Fb
#define OUTPUT_5_WIDTH       1
#define OUTPUT_DIMS_5_COL    1
#define OUTPUT_5_DTYPE       real_T
#define OUTPUT_5_COMPLEX     COMPLEX_NO
#define OUT_5_FRAME_BASED    FRAME_NO
#define OUT_5_BUS_BASED      0
#define OUT_5_BUS_NAME       
#define OUT_5_DIMS           1-D
#define OUT_5_ISSIGNED        1
#define OUT_5_WORDLENGTH      8
#define OUT_5_FIXPOINTSCALING 1
#define OUT_5_FRACTIONLENGTH  3
#define OUT_5_BIAS            0
#define OUT_5_SLOPE           0.125
/* Output Port  6 */
#define OUT_PORT_6_NAME      Vb
#define OUTPUT_6_WIDTH       1
#define OUTPUT_DIMS_6_COL    1
#define OUTPUT_6_DTYPE       real_T
#define OUTPUT_6_COMPLEX     COMPLEX_NO
#define OUT_6_FRAME_BASED    FRAME_NO
#define OUT_6_BUS_BASED      0
#define OUT_6_BUS_NAME       
#define OUT_6_DIMS           1-D
#define OUT_6_ISSIGNED        1
#define OUT_6_WORDLENGTH      8
#define OUT_6_FIXPOINTSCALING 1
#define OUT_6_FRACTIONLENGTH  3
#define OUT_6_BIAS            0
#define OUT_6_SLOPE           0.125
#define OUT_PORT_7_NAME      pb
#define OUTPUT_7_WIDTH       1
#define OUTPUT_DIMS_7_COL    1
#define OUTPUT_7_DTYPE       real_T
#define OUTPUT_7_COMPLEX     COMPLEX_NO
#define OUT_7_FRAME_BASED    FRAME_NO
#define OUT_7_BUS_BASED      0
#define OUT_7_BUS_NAME       
#define OUT_7_DIMS           1-D
#define OUT_7_ISSIGNED        1
#define OUT_7_WORDLENGTH      8
#define OUT_7_FIXPOINTSCALING 1
#define OUT_7_FRACTIONLENGTH  3
#define OUT_7_BIAS            0
#define OUT_7_SLOPE           0.125

#define NPARAMS               10    
/* Parameter  1 */
#define PARAMETER_0_NAME      fs
#define PARAMETER_0_DTYPE     real_T
#define PARAMETER_0_COMPLEX   COMPLEX_NO
/* Parameter  2 */
#define PARAMETER_1_NAME      DPhiMix
#define PARAMETER_1_DTYPE     real_T
#define PARAMETER_1_COMPLEX   COMPLEX_NO
/* Parameter  3 */
#define PARAMETER_2_NAME      phiMix0
#define PARAMETER_2_DTYPE     real_T
#define PARAMETER_2_COMPLEX   COMPLEX_NO
/* Parameter  4 */
#define PARAMETER_3_NAME      alpha
#define PARAMETER_3_DTYPE     real_T
#define PARAMETER_3_COMPLEX   COMPLEX_NO
/* Parameter  5 */
#define PARAMETER_4_NAME      hn
#define PARAMETER_4_DTYPE     real_T
#define PARAMETER_4_COMPLEX   COMPLEX_NO
/* Parameter  6 */
#define PARAMETER_5_NAME      m0
#define PARAMETER_5_DTYPE     real_T
#define PARAMETER_5_COMPLEX   COMPLEX_NO
/* Parameter  7 */
#define PARAMETER_6_NAME      E0
#define PARAMETER_6_DTYPE     real_T
#define PARAMETER_6_COMPLEX   COMPLEX_NO
/* Parameter  8 */
#define PARAMETER_7_NAME      mb0
#define PARAMETER_7_DTYPE     real_T
#define PARAMETER_7_COMPLEX   COMPLEX_NO
/* Parameter  9 */
#define PARAMETER_8_NAME      V0
#define PARAMETER_8_DTYPE     real_T
#define PARAMETER_8_COMPLEX   COMPLEX_NO
/* Parameter  10 */
#define PARAMETER_9_NAME      nStroke
#define PARAMETER_9_DTYPE     real_T
#define PARAMETER_9_COMPLEX   COMPLEX_NO

/*definition related to DWork Vectors*/
#define NDWORKS              24
// DWork 0
#define DWORK_0_NAME         p_prev
#define DWORK_0_WIDTH        1
#define DWORK_0_DTYPE        real_T
#define DWORK_0_COMPLEX      COMPLEX_NO
// DWork 1
#define DWORK_1_NAME         Tu_prev
#define DWORK_1_WIDTH        1
#define DWORK_1_DTYPE        real_T
#define DWORK_1_COMPLEX      COMPLEX_NO
// DWork2
#define DWORK_2_NAME         Fu_prev
#define DWORK_2_WIDTH        1
#define DWORK_2_DTYPE        real_T
#define DWORK_2_COMPLEX      COMPLEX_NO
// DWork3
#define DWORK_3_NAME         Ru_prev
#define DWORK_3_WIDTH        1
#define DWORK_3_DTYPE        real_T
#define DWORK_3_COMPLEX      COMPLEX_NO
// DWork 4
#define DWORK_4_NAME         uu_prev
#define DWORK_4_WIDTH        1
#define DWORK_4_DTYPE        real_T
#define DWORK_4_COMPLEX      COMPLEX_NO
// DWork 5
#define DWORK_5_NAME         Cvu_prev
#define DWORK_5_WIDTH        1
#define DWORK_5_DTYPE        real_T
#define DWORK_5_COMPLEX      COMPLEX_NO
// DWork 6
#define DWORK_6_NAME         Tb_prev
#define DWORK_6_WIDTH        1
#define DWORK_6_DTYPE        real_T
#define DWORK_6_COMPLEX      COMPLEX_NO
// DWork 7
#define DWORK_7_NAME         Fb_prev
#define DWORK_7_WIDTH        1
#define DWORK_7_DTYPE        real_T
#define DWORK_7_COMPLEX      COMPLEX_NO
// DWork 8
#define DWORK_8_NAME         Rb_prev
#define DWORK_8_WIDTH        1
#define DWORK_8_DTYPE        real_T
#define DWORK_8_COMPLEX      COMPLEX_NO
// DWork 9
#define DWORK_9_NAME         ub_prev
#define DWORK_9_WIDTH        1
#define DWORK_9_DTYPE        real_T
#define DWORK_9_COMPLEX      COMPLEX_NO
// DWork 10
#define DWORK_10_NAME        Cvb_prev
#define DWORK_10_WIDTH        1
#define DWORK_10_DTYPE        real_T
#define DWORK_10_COMPLEX      COMPLEX_NO
// DWork 12
#define DWORK_11_NAME         mCyl_prev
#define DWORK_11_WIDTH        1
#define DWORK_11_DTYPE        real_T
#define DWORK_11_COMPLEX      COMPLEX_NO
// DWork 13
#define DWORK_12_NAME         mbCyl_prev
#define DWORK_12_WIDTH        1
#define DWORK_12_DTYPE        real_T
#define DWORK_12_COMPLEX      COMPLEX_NO
// DWork 14
#define DWORK_13_NAME         VCyl_prev
#define DWORK_13_WIDTH        1
#define DWORK_13_DTYPE        real_T
#define DWORK_13_COMPLEX      COMPLEX_NO
// DWork 15
#define DWORK_14_NAME         QCyl_prev
#define DWORK_14_WIDTH        1
#define DWORK_14_DTYPE        real_T
#define DWORK_14_COMPLEX      COMPLEX_NO
// DWork 16
#define DWORK_15_NAME         HCyl_prev
#define DWORK_15_WIDTH        1
#define DWORK_15_DTYPE        real_T
#define DWORK_15_COMPLEX      COMPLEX_NO
// DWork 17
#define DWORK_16_NAME         WCyl_prev
#define DWORK_16_WIDTH        1
#define DWORK_16_DTYPE        real_T
#define DWORK_16_COMPLEX      COMPLEX_NO
// DWork 18
#define DWORK_17_NAME         mu_prev
#define DWORK_17_WIDTH        1
#define DWORK_17_DTYPE        real_T
#define DWORK_17_COMPLEX      COMPLEX_NO
// DWork 19
#define DWORK_18_NAME         mub_prev
#define DWORK_18_WIDTH        1
#define DWORK_18_DTYPE        real_T
#define DWORK_18_COMPLEX      COMPLEX_NO
// DWork 20
#define DWORK_19_NAME         Vu_prev
#define DWORK_19_WIDTH        1
#define DWORK_19_DTYPE        real_T
#define DWORK_19_COMPLEX      COMPLEX_NO
// DWork 21
#define DWORK_20_NAME         mfb_prev
#define DWORK_20_WIDTH        1
#define DWORK_20_DTYPE        real_T
#define DWORK_20_COMPLEX      COMPLEX_NO
// DWork 22
#define DWORK_21_NAME         mMixPrev
#define DWORK_21_WIDTH        1
#define DWORK_21_DTYPE        real_T
#define DWORK_21_COMPLEX      COMPLEX_NO
// DWork 23
#define DWORK_22_NAME         mb0
#define DWORK_22_WIDTH        1
#define DWORK_22_DTYPE        real_T
#define DWORK_22_COMPLEX      COMPLEX_NO
// DWork 24
#define DWORK_23_NAME         resetMix
#define DWORK_23_WIDTH        1
#define DWORK_23_DTYPE        real_T
#define DWORK_23_COMPLEX      COMPLEX_NO


/*end of definition related to DWork Vectors*/

#define SAMPLE_TIME_0        INHERITED_SAMPLE_TIME
#define NUM_DISC_STATES      0
#define DISC_STATES_IC       [0]
#define NUM_CONT_STATES      7
#define CONT_STATES_IC       [0]

#define SFUNWIZ_GENERATE_TLC 1
#define SOURCEFILES "__SFB__GetPTF.c__SFB__GetThdynCombGasZach.c"
#define PANELINDEX           6
#define USE_SIMSTRUCT        0
#define SHOW_COMPILE_STEPS   0                   
#define CREATE_DEBUG_MEXFILE 0
#define SAVE_CODE_ONLY       0
#define SFUNWIZ_REVISION     3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#define PARAM_DEF0(S) ssGetSFcnParam(S, 0)
#define PARAM_DEF1(S) ssGetSFcnParam(S, 1)
#define PARAM_DEF2(S) ssGetSFcnParam(S, 2)
#define PARAM_DEF3(S) ssGetSFcnParam(S, 3)
#define PARAM_DEF4(S) ssGetSFcnParam(S, 4)
#define PARAM_DEF5(S) ssGetSFcnParam(S, 5)
#define PARAM_DEF6(S) ssGetSFcnParam(S, 6)
#define PARAM_DEF7(S) ssGetSFcnParam(S, 7)
#define PARAM_DEF8(S) ssGetSFcnParam(S, 8)
#define PARAM_DEF9(S) ssGetSFcnParam(S, 9)

#define IS_PARAM_DOUBLE(pVal) (mxIsNumeric(pVal) && !mxIsLogical(pVal) &&\
!mxIsEmpty(pVal) && !mxIsSparse(pVal) && !mxIsComplex(pVal) && mxIsDouble(pVal))

extern void ThdynCVNV2Zone_Output_wrapper(const real_T     *FComb,
                                 const real_T       *phi,
                                 real_T             *p,
                                 real_T             *Tu,
                                 real_T             *Fu,
                                 real_T             *Vu,
                                 real_T             *Tb,
                                 real_T             *Fb,
                                 real_T             *Vb,
								 real_T             *pb,
                                 const real_T       *xC, 
                                 const real_T       *p_prev,        
                                 const real_T       *Tu_prev,
                                 const real_T       *Fu_prev,
                                 const real_T       *Ru_prev,
                                 const real_T       *uu_Prev,
                                 const real_T       *Cvu_prev,
                                 const real_T       *Tb_prev,
                                 const real_T       *Fb_prev,
                                 const real_T       *Rb_prev,
                                 const real_T       *ub_prev,
                                 const real_T       *Cvb_prev,
                                 const real_T       *mCyl_prev,
                                 const real_T       *mbCyl_prev,
                                 const real_T       *VCyl_prev,
                                 const real_T       *QCyl_prev,
                                 const real_T       *HCyl_prev,        
                                 const real_T       *WCyl_prev,        
                                 const real_T       *mu_prev,
                                 const real_T       *mub_prev,
                                 const real_T       *Vu_prev,
                                 const real_T       *mfb_prev,
                                 const real_T       *mMix_prev,
                                 const real_T       *mb0,
                                 const real_T  *fs,  const int_T  p_width0,
                                 const real_T *DPhiMix, const int_T p_width1,
                                 const real_T *phiMix0, const int_T p_width2,
                                 const real_T *alpha, const int_T p_width3,
								 const real_T *hn, const int_T p_width4,
                                 const real_T *nStroke, const int_T p_width9);

extern void ThdynCVNV2Zone_Derivatives_wrapper(const real_T *dm,
                          const real_T *dmb,
                          const real_T *dV,
                          const real_T *dmfb,
                          const real_T *dQCyl,
                          const real_T *dHCyl,
						  const real_T *dWCyl,
                          real_T *dx);

extern void ThdynCVNV2Zone_Update_wrapper(const real_T *phi,
                          const real_T *FComb,
                          const real_T *combState,
                          const real_T *p,
                          const real_T *Tu,
                          const real_T *Fu,
                          const real_T *Vu,
                          const real_T *Tb,
                          const real_T *Fb,
                          const real_T *Vb,
                          const real_T *xC,
                          real_T *p_prev,        
                          real_T *Tu_prev,
                          real_T *Fu_prev,
                          real_T *Ru_prev,
                          real_T *uu_Prev,
                          real_T *Cvu_prev,
                          real_T *Tb_prev,
                          real_T *Fb_prev,
                          real_T *Rb_prev,
                          real_T *ub_prev,
                          real_T *Cvb_prev,
                          real_T *mCyl_prev,
                          real_T *mbCyl_prev,
                          real_T *VCyl_prev,
                          real_T *QCyl_prev,
                          real_T *HCyl_prev,        
                          real_T *WCyl_prev,        
                          real_T *mu_prev,
                          real_T *mub_prev,
                          real_T *Vu_prev,
                          real_T *mfb_prev,
                          real_T *mMix_prev,
                          real_T *mb0,
                          real_T *ResetMix,        
                          const real_T  *fs,  const int_T  p_width1,
                          const real_T *DPhiMix, const int_T p_width3,
                          const real_T *phiMix0, const int_T p_width4,
                          const real_T *alpha, const int_T p_width5,
						  const real_T *hn, const int_T p_width6,
                          const real_T *nStroke, const int_T p_width7);

/*====================*
 * S-function methods *
 *====================*/
#define MDL_CHECK_PARAMETERS
 #if defined(MDL_CHECK_PARAMETERS) && defined(MATLAB_MEX_FILE)
   /* Function: mdlCheckParameters =============================================
     * Abstract:
     *    Validate our parameters to verify they are okay.
     */
    static void mdlCheckParameters(SimStruct *S)
    {
     int paramIndex  = 0;
     bool validParam = false;
     /* All parameters must match the S-function Builder Dialog */
     

	 {
	  const mxArray *pVal0 = ssGetSFcnParam(S,0);
	  if (!IS_PARAM_DOUBLE(pVal0)) {
	    validParam = true;
	    paramIndex = 0;
	    goto EXIT_POINT;
	  }
	 }
     
     {
	  const mxArray *pVal1 = ssGetSFcnParam(S,1);
	  if (!IS_PARAM_DOUBLE(pVal1)) {
	    validParam = true;
	    paramIndex = 1;
	    goto EXIT_POINT;
	  }
	 }
     
     {
	  const mxArray *pVal2 = ssGetSFcnParam(S,2);
	  if (!IS_PARAM_DOUBLE(pVal2)) {
	    validParam = true;
	    paramIndex = 2;
	    goto EXIT_POINT;
	  }
	 }
     
     {
	  const mxArray *pVal3 = ssGetSFcnParam(S,3);
	  if (!IS_PARAM_DOUBLE(pVal3)) {
	    validParam = true;
	    paramIndex = 3;
	    goto EXIT_POINT;
	  }
	 }     

     {
	  const mxArray *pVal4 = ssGetSFcnParam(S,4);
	  if (!IS_PARAM_DOUBLE(pVal4)) {
	    validParam = true;
	    paramIndex = 4;
	    goto EXIT_POINT;
	  }
	 }

     {
	  const mxArray *pVal5 = ssGetSFcnParam(S,5);
	  if (!IS_PARAM_DOUBLE(pVal5)) {
	    validParam = true;
	    paramIndex = 5;
	    goto EXIT_POINT;
	  }
	 }

     {
	  const mxArray *pVal6 = ssGetSFcnParam(S,6);
	  if (!IS_PARAM_DOUBLE(pVal6)) {
	    validParam = true;
	    paramIndex = 6;
	    goto EXIT_POINT;
	  }
	 }

     {
	  const mxArray *pVal7 = ssGetSFcnParam(S,7);
	  if (!IS_PARAM_DOUBLE(pVal7)) {
	    validParam = true;
	    paramIndex = 7;
	    goto EXIT_POINT;
	  }
	 }

     {
	  const mxArray *pVal8 = ssGetSFcnParam(S,8);
	  if (!IS_PARAM_DOUBLE(pVal8)) {
	    validParam = true;
	    paramIndex = 8;
	    goto EXIT_POINT;
	  }
	 }

     {
	  const mxArray *pVal9 = ssGetSFcnParam(S,9);
	  if (!IS_PARAM_DOUBLE(pVal9)) {
	    validParam = true;
	    paramIndex = 9;
	    goto EXIT_POINT;
	  }
	 }

     EXIT_POINT:
      if (validParam) {
          char parameterErrorMsg[1024];
          sprintf(parameterErrorMsg, "The data type and or complexity of parameter  %d does not match the "
                  "information specified in the S-function Builder dialog. "
                  "For non-double parameters you will need to cast them using int8, int16, "
                  "int32, uint8, uint16, uint32 or boolean.", paramIndex + 1);
	  ssSetErrorStatus(S,parameterErrorMsg);
      }
	return;
    }
 #endif /* MDL_CHECK_PARAMETERS */
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);  /* Number of expected parameters */
      #if defined(MATLAB_MEX_FILE)
	if (ssGetNumSFcnParams(S) == ssGetSFcnParamsCount(S)) {
	  mdlCheckParameters(S);
	  if (ssGetErrorStatus(S) != NULL) {
	    return;
	  }
	 } else {
	   return; /* Parameter mismatch will be reported by Simulink */
	 }
      #endif

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);

    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /*Input Port 0 */
    ssSetInputPortWidth(S,  0, INPUT_0_WIDTH); /* */
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /*Input Port 1 */
    ssSetInputPortWidth(S,  1, INPUT_1_WIDTH); /* */
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /*Input Port 2 */
    ssSetInputPortWidth(S,  2, INPUT_2_WIDTH); /* */
    ssSetInputPortDataType(S, 2, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/

    /*Input Port 3 */
    ssSetInputPortWidth(S,  3, INPUT_3_WIDTH); /* */
    ssSetInputPortDataType(S, 3, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  3, INPUT_3_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 3, INPUT_3_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 3, 1); /*direct input signal access*/

    /*Input Port 4 */
    ssSetInputPortWidth(S,  4, INPUT_4_WIDTH); /* */
    ssSetInputPortDataType(S, 4, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  4, INPUT_4_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 4, INPUT_4_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 4, 1); /*direct input signal access*/
    /*Input Port 5 */
    ssSetInputPortWidth(S,  5, INPUT_5_WIDTH); /* */
    ssSetInputPortDataType(S, 5, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  5, INPUT_5_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 5, INPUT_5_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 5, 1); /*direct input signal access*/
    /*Input Port 6 */
    ssSetInputPortWidth(S,  6, INPUT_6_WIDTH); /* */
    ssSetInputPortDataType(S, 6, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  6, INPUT_6_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 6, INPUT_6_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 6, 1); /*direct input signal access*/
    /*Input Port 7 */
    ssSetInputPortWidth(S,  7, INPUT_7_WIDTH); /* */
    ssSetInputPortDataType(S, 7, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  7, INPUT_7_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 7, INPUT_7_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 7, 1); /*direct input signal access*/
    /*Input Port 8 */
    ssSetInputPortWidth(S,  8, INPUT_8_WIDTH); /* */
    ssSetInputPortDataType(S, 8, SS_DOUBLE);
    ssSetInputPortComplexSignal(S,  8, INPUT_8_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 8, INPUT_8_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 8, 1); /*direct input signal access*/    
	/*Input Port 9 */
	ssSetInputPortWidth(S, 9, INPUT_9_WIDTH); /* */
	ssSetInputPortDataType(S, 9, SS_DOUBLE);
	ssSetInputPortComplexSignal(S, 9, INPUT_9_COMPLEX);
	ssSetInputPortDirectFeedThrough(S, 9, INPUT_9_FEEDTHROUGH);
	ssSetInputPortRequiredContiguous(S, 9, 1); /*direct input signal access*/

    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortDataType(S, 1, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    /* Output Port 2 */
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortDataType(S, 2, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    /* Output Port 3 */
    ssSetOutputPortWidth(S, 3, OUTPUT_3_WIDTH);
    ssSetOutputPortDataType(S, 3, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 3, OUTPUT_3_COMPLEX);
    /* Output Port 4 */
    ssSetOutputPortWidth(S, 4, OUTPUT_4_WIDTH);
    ssSetOutputPortDataType(S, 4, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 4, OUTPUT_4_COMPLEX);
    /* Output Port 5 */
    ssSetOutputPortWidth(S, 5, OUTPUT_5_WIDTH);
    ssSetOutputPortDataType(S, 5, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 5, OUTPUT_5_COMPLEX);
    /* Output Port 6 */
    ssSetOutputPortWidth(S, 6, OUTPUT_6_WIDTH);
    ssSetOutputPortDataType(S, 6, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 6, OUTPUT_6_COMPLEX);
	/* Output Port 7 */
	ssSetOutputPortWidth(S, 7, OUTPUT_7_WIDTH);
	ssSetOutputPortDataType(S, 7, SS_DOUBLE);
	ssSetOutputPortComplexSignal(S, 7, OUTPUT_7_COMPLEX);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumPWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    /*initialzation of sizes related to DWork Vectors*/
    ssSetNumDWork(S,NDWORKS);
    /*DWork vector 1*/
    ssSetDWorkWidth(S, 0, DWORK_0_WIDTH);
    ssSetDWorkDataType(S, 0, SS_DOUBLE);
    ssSetDWorkWidth(S, 1, DWORK_1_WIDTH);
    ssSetDWorkDataType(S, 1, SS_DOUBLE);
    ssSetDWorkWidth(S, 2, DWORK_2_WIDTH);
    ssSetDWorkDataType(S, 2, SS_DOUBLE);
    ssSetDWorkWidth(S, 3, DWORK_3_WIDTH);
    ssSetDWorkDataType(S, 3, SS_DOUBLE);
    ssSetDWorkWidth(S, 4, DWORK_4_WIDTH);
    ssSetDWorkDataType(S, 4, SS_DOUBLE);
    ssSetDWorkWidth(S, 5, DWORK_5_WIDTH);
    ssSetDWorkDataType(S, 5, SS_DOUBLE);
    ssSetDWorkWidth(S, 6, DWORK_6_WIDTH);
    ssSetDWorkDataType(S, 6, SS_DOUBLE);
    ssSetDWorkWidth(S, 7, DWORK_7_WIDTH);
    ssSetDWorkDataType(S, 7, SS_DOUBLE);
    ssSetDWorkWidth(S, 8, DWORK_8_WIDTH);
    ssSetDWorkDataType(S, 8, SS_DOUBLE);
    ssSetDWorkWidth(S, 9, DWORK_9_WIDTH);
    ssSetDWorkDataType(S, 9, SS_DOUBLE);
    ssSetDWorkWidth(S, 10, DWORK_10_WIDTH);
    ssSetDWorkDataType(S, 10, SS_DOUBLE);    
    ssSetDWorkWidth(S, 11, DWORK_11_WIDTH);
    ssSetDWorkDataType(S, 11, SS_DOUBLE);    
	ssSetDWorkWidth(S, 12, DWORK_12_WIDTH);
    ssSetDWorkDataType(S, 12, SS_DOUBLE);    
	ssSetDWorkWidth(S, 13, DWORK_13_WIDTH);
    ssSetDWorkDataType(S, 13, SS_DOUBLE);    
    ssSetDWorkWidth(S, 14, DWORK_14_WIDTH);
    ssSetDWorkDataType(S, 14, SS_DOUBLE);    
    ssSetDWorkWidth(S, 15, DWORK_15_WIDTH);
    ssSetDWorkDataType(S, 15, SS_DOUBLE);    
    ssSetDWorkWidth(S, 16, DWORK_16_WIDTH);
    ssSetDWorkDataType(S, 16, SS_DOUBLE);    
    ssSetDWorkWidth(S, 17, DWORK_17_WIDTH);
    ssSetDWorkDataType(S, 17, SS_DOUBLE);    
    ssSetDWorkWidth(S, 18, DWORK_18_WIDTH);
    ssSetDWorkDataType(S, 18, SS_DOUBLE);    
    ssSetDWorkWidth(S, 19, DWORK_19_WIDTH);
    ssSetDWorkDataType(S, 19, SS_DOUBLE);    
    ssSetDWorkWidth(S, 20, DWORK_20_WIDTH);
    ssSetDWorkDataType(S, 20, SS_DOUBLE);    
    ssSetDWorkWidth(S, 21, DWORK_21_WIDTH);
    ssSetDWorkDataType(S, 21, SS_DOUBLE);    
    ssSetDWorkWidth(S, 22, DWORK_22_WIDTH);
    ssSetDWorkDataType(S, 22, SS_DOUBLE);    
    ssSetDWorkWidth(S, 23, DWORK_23_WIDTH);
    ssSetDWorkDataType(S, 23, SS_DOUBLE);    

	
  
    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR | 
		     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

# define MDL_SET_INPUT_PORT_FRAME_DATA
static void mdlSetInputPortFrameData(SimStruct  *S, 
                                     int_T      port,
                                     Frame_T    frameData)
{
    ssSetInputPortFrameData(S, port, frameData);
}
/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_INITIALIZE_CONDITIONS
 /* Function: mdlInitializeConditions ========================================
  * Abstract:
  *    Initialize the states
  */
 static void mdlInitializeConditions(SimStruct *S)
 {
   #define MDL_INITIALIZE_CONDITIONS
/* Function: mdlInitializeConditions ============================
* Abstract:
* Initialize both continuous states to zero
*/
   real_T *xC   = ssGetContStates(S);
   
    const real_T  *fs  = (const real_T *)mxGetData(PARAM_DEF0(S));
    const real_T  *m0  = (const real_T *)mxGetData(PARAM_DEF5(S));
    const real_T  *E0  = (const real_T *)mxGetData(PARAM_DEF6(S));
    const real_T  *mb0  = (const real_T *)mxGetData(PARAM_DEF7(S));
    const real_T  *V0  = (const real_T *)mxGetData(PARAM_DEF8(S));
    const real_T  *alpha = (const real_T *)mxGetData(PARAM_DEF3(S));
    
    real_T *p_prev = (real_T*) ssGetDWork(S,0);      
    real_T *Tu_prev = (real_T*) ssGetDWork(S,1);
    real_T *Fu_prev = (real_T*) ssGetDWork(S,2);
    real_T *Ru_prev = (real_T*) ssGetDWork(S,3);
    real_T *uu_prev = (real_T*) ssGetDWork(S,4);    
	real_T *Cvu_prev = (real_T*) ssGetDWork(S,5);    
    real_T *Tb_prev = (real_T*) ssGetDWork(S,6);
    real_T *Fb_prev = (real_T*) ssGetDWork(S,7);
    real_T *Rb_prev = (real_T*) ssGetDWork(S,8);
    real_T *ub_prev = (real_T*) ssGetDWork(S,9);    
	real_T *Cvb_prev = (real_T*) ssGetDWork(S,10);  
    real_T *mCyl_prev = (real_T*) ssGetDWork(S,11);
    real_T *mbCyl_prev = (real_T*) ssGetDWork(S,12);
    real_T *VCyl_prev = (real_T*) ssGetDWork(S,13);
    real_T *mu_prev = (real_T*) ssGetDWork(S,14);
    real_T *mub_prev = (real_T*) ssGetDWork(S,15);
    real_T *Vu_prev = (real_T*) ssGetDWork(S,16);
    real_T *QCyl_prev = (real_T*) ssGetDWork(S,17);
    real_T *HCyl_prev = (real_T*) ssGetDWork(S,18);        
    real_T *WCyl_prev = (real_T*) ssGetDWork(S,19);        
    real_T *mfb_prev = (real_T*) ssGetDWork(S,20);
    real_T *mMix_prev = (real_T*) ssGetDWork(S,21);
    real_T *mbb0 = (real_T*) ssGetDWork(S,22);
    real_T *ResetMix = (real_T*) ssGetDWork(S,23);
                                 
    xC[0] = m0[0]; 
    xC[1] = mb0[0];
    xC[2] = V0[0];
    xC[3] = 0;
	xC[4] = 0;
	xC[5] = E0[0];
	xC[6] = 0;
   
    GetPTFV1(m0[0],mb0[0],E0[0],V0[0],300,287,2.1386e5,718.7,fs[0], 
            p_prev,Tu_prev,Fu_prev);
    Ru_prev[0] = 287;
    uu_prev[0] = E0[0]/m0[0];
    Cvu_prev[0] = 718.7221;
    Tb_prev[0] = Tu_prev[0];
    Fb_prev[0] = Fu_prev[0];
    Rb_prev[0] = 287;
	ub_prev[0] = E0[0] / m0[0];
    Cvb_prev[0] = 718.7221;
    mCyl_prev[0] = m0[0];
    mbCyl_prev[0] = mb0[0];
    VCyl_prev[0] = V0[0];
    mu_prev[0] = m0[0]*(1-alpha[0]);
    mub_prev[0] = mb0[0]*(1-alpha[0]);
    Vu_prev[0] = V0[0]*(1-alpha[0]);
    QCyl_prev[0] = 0;
    HCyl_prev[0] = E0[0];
    WCyl_prev[0] = 0;
    mfb_prev[0] = 0;
    mMix_prev[0] = 0;
    mbb0[0] = 0;
    ResetMix[0] = 1;
}


#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType( S, 0, dType);
}
#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
  ssSetInputPortDataType( S, 0, SS_DOUBLE);
 ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}
/* Function: mdlOutputs =======================================================
 *
*/
static void mdlOutputs(SimStruct *S, int_T tid)
{
    
    const real_T *FComb = (const real_T*) ssGetInputPortSignal(S,7);
    const real_T *phi = (const real_T*) ssGetInputPortSignal(S,8);
    
    const real_T *xC   = ssGetContStates(S);
    real_T        *pCyl  = (real_T *)ssGetOutputPortRealSignal(S,7);
    real_T        *TCyl  = (real_T *)ssGetOutputPortRealSignal(S,8);
    real_T        *FCyl  = (real_T *)ssGetOutputPortRealSignal(S,9);
    real_T        *VCyl  = (real_T *)ssGetOutputPortRealSignal(S,10);
    real_T        *p = (real_T *)ssGetOutputPortRealSignal(S,0);
    real_T        *Tu = (real_T *)ssGetOutputPortRealSignal(S,1);
    real_T        *Fu = (real_T *)ssGetOutputPortRealSignal(S,2);
    real_T        *Vu = (real_T *)ssGetOutputPortRealSignal(S,3);
    real_T        *Tb = (real_T *)ssGetOutputPortRealSignal(S,4);
    real_T        *Fb = (real_T *)ssGetOutputPortRealSignal(S,5);
    real_T        *Vb = (real_T *)ssGetOutputPortRealSignal(S,6);
	real_T        *pb = (real_T *)ssGetOutputPortRealSignal(S, 7);
    real_T *p_prev = (real_T*) ssGetDWork(S,0);      
    real_T *Tu_prev = (real_T*) ssGetDWork(S,1);
    real_T *Fu_prev = (real_T*) ssGetDWork(S,2);
    real_T *Ru_prev = (real_T*) ssGetDWork(S,3);
    real_T *uu_prev = (real_T*) ssGetDWork(S,4);    
	real_T *Cvu_prev = (real_T*) ssGetDWork(S,5);    
    real_T *Tb_prev = (real_T*) ssGetDWork(S,6);
    real_T *Fb_prev = (real_T*) ssGetDWork(S,7);
    real_T *Rb_prev = (real_T*) ssGetDWork(S,8);
    real_T *ub_prev = (real_T*) ssGetDWork(S,9);    
	real_T *Cvb_prev = (real_T*) ssGetDWork(S,10);  
    real_T *mCyl_prev = (real_T*) ssGetDWork(S,11);
    real_T *mbCyl_prev = (real_T*) ssGetDWork(S,12);
    real_T *VCyl_prev = (real_T*) ssGetDWork(S,13);
    real_T *mu_prev = (real_T*) ssGetDWork(S,14);
    real_T *mub_prev = (real_T*) ssGetDWork(S,15);
    real_T *Vu_prev = (real_T*) ssGetDWork(S,16);
    real_T *QCyl_prev = (real_T*) ssGetDWork(S,17);
    real_T *HCyl_prev = (real_T*) ssGetDWork(S,18);        
    real_T *WCyl_prev = (real_T*) ssGetDWork(S,19);        
    real_T *mfb_prev = (real_T*) ssGetDWork(S,20);
    real_T *mMix_prev = (real_T*) ssGetDWork(S,21);
    real_T *mb0 = (real_T*) ssGetDWork(S,22);

    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
	const int_T   p_width4  = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));

    const real_T  *fs  = (const real_T *)mxGetData(PARAM_DEF0(S));
	const real_T  *DPhiMix  = (const real_T *)mxGetData(PARAM_DEF1(S));
    const real_T  *phiMix0  = (const real_T *)mxGetData(PARAM_DEF2(S));
    const real_T  *alpha  = (const real_T *)mxGetData(PARAM_DEF3(S));
	const real_T  *hn = (const real_T *)mxGetData(PARAM_DEF4(S));
	const real_T  *nStroke  = (const real_T *)mxGetData(PARAM_DEF9(S));
    
    ThdynCVNV2Zone_Output_wrapper(FComb,phi,p,Tu,Fu,Vu,Tb,Fb,Vb,pb,xC, 
            p_prev,Tu_prev,Fu_prev,Ru_prev,uu_prev,Cvu_prev,Tb_prev,
            Fb_prev,Rb_prev,ub_prev,Cvb_prev,mCyl_prev,mbCyl_prev,
            VCyl_prev,QCyl_prev,HCyl_prev,WCyl_prev,
			mu_prev, mub_prev, Vu_prev,mfb_prev, mMix_prev, mb0,
            fs,p_width0,DPhiMix,p_width1,phiMix0,p_width2,
			alpha,p_width3,hn,p_width4,nStroke, p_width9);
    
}

#define MDL_DERIVATIVES  /* Change to #undef to remove function */
/* Function: mdlDerivatives =================================================
   * Abstract:
   *    In this function, you compute the S-function block's derivatives.
   *    The derivatives are placed in the derivative vector, ssGetdX(S).
   */
  static void mdlDerivatives(SimStruct *S)
  {
    const real_T   *dm  = (const real_T*) ssGetInputPortSignal(S,0);
    const real_T   *dmf  = (const real_T*) ssGetInputPortSignal(S,1);
    const real_T   *dV  = (const real_T*) ssGetInputPortSignal(S,2);
    const real_T   *dmfb  = (const real_T*) ssGetInputPortSignal(S,3);
    const real_T   *dQCyl  = (const real_T*) ssGetInputPortSignal(S,4);
    const real_T   *dHCyl  = (const real_T*) ssGetInputPortSignal(S,5);
	const real_T   *dWCyl = (const real_T*)ssGetInputPortSignal(S, 6);
    real_T         *dx  = ssGetdX(S);

    ThdynCVNV2Zone_Derivatives_wrapper(dm,dmf,dV,dmfb,dQCyl,dHCyl,dWCyl,dx);
  }
  

#define MDL_UPDATE  /* Change to #undef to remove function */
/* Function: mdlUpdate ======================================================
   * Abstract:
   *    This function is called once for every major integration time step.
   *    Discrete states are typically updated here, but this function is useful
   *    for performing any tasks that should only take place once per
   *    integration step.
   */
static void mdlUpdate(SimStruct *S, int_T tid)
{
    const real_T *FComb = (const real_T*) ssGetInputPortSignal(S,7);
    const real_T *phi = (const real_T*) ssGetInputPortSignal(S,8);
    const real_T *combState = (const real_T*) ssGetInputPortSignal(S,9);
    real_T        *p = (real_T *)ssGetOutputPortRealSignal(S,0);
    real_T        *Tu = (real_T *)ssGetOutputPortRealSignal(S,1);
    real_T        *Fu = (real_T *)ssGetOutputPortRealSignal(S,2);
    real_T        *Vu = (real_T *)ssGetOutputPortRealSignal(S,3);
    real_T        *Tb = (real_T *)ssGetOutputPortRealSignal(S,4);
    real_T        *Fb = (real_T *)ssGetOutputPortRealSignal(S,5);
    real_T        *Vb = (real_T *)ssGetOutputPortRealSignal(S,6);
    const real_T *xC = ssGetContStates(S);
    real_T *p_prev = (real_T*) ssGetDWork(S,0);      
    real_T *Tu_prev = (real_T*) ssGetDWork(S,1);
    real_T *Fu_prev = (real_T*) ssGetDWork(S,2);
    real_T *Ru_prev = (real_T*) ssGetDWork(S,3);
    real_T *uu_prev = (real_T*) ssGetDWork(S,4);    
	real_T *Cvu_prev = (real_T*) ssGetDWork(S,5);    
    real_T *Tb_prev = (real_T*) ssGetDWork(S,6);
    real_T *Fb_prev = (real_T*) ssGetDWork(S,7);
    real_T *Rb_prev = (real_T*) ssGetDWork(S,8);
    real_T *ub_prev = (real_T*) ssGetDWork(S,9);    
	real_T *Cvb_prev = (real_T*) ssGetDWork(S,10);  
    real_T *mCyl_prev = (real_T*) ssGetDWork(S,11);
    real_T *mbCyl_prev = (real_T*) ssGetDWork(S,12);
    real_T *VCyl_prev = (real_T*) ssGetDWork(S,13);
    real_T *mu_prev = (real_T*) ssGetDWork(S,14);
    real_T *mub_prev = (real_T*) ssGetDWork(S,15);
    real_T *Vu_prev = (real_T*) ssGetDWork(S,16);
    real_T *QCyl_prev = (real_T*) ssGetDWork(S,17);
    real_T *HCyl_prev = (real_T*) ssGetDWork(S,18);        
    real_T *WCyl_prev = (real_T*) ssGetDWork(S,19);        
    real_T *mfb_prev = (real_T*) ssGetDWork(S,20);
    real_T *mMix_prev = (real_T*) ssGetDWork(S,21);
    real_T *mb0 = (real_T*) ssGetDWork(S,22);
    real_T *ResetMix = (real_T*) ssGetDWork(S,23);
    
    const int_T   p_width0  = mxGetNumberOfElements(PARAM_DEF0(S));
    const int_T   p_width1  = mxGetNumberOfElements(PARAM_DEF1(S));
    const int_T   p_width2  = mxGetNumberOfElements(PARAM_DEF2(S));
    const int_T   p_width3  = mxGetNumberOfElements(PARAM_DEF3(S));
	const int_T   p_width4 = mxGetNumberOfElements(PARAM_DEF4(S));
    const int_T   p_width9  = mxGetNumberOfElements(PARAM_DEF9(S));

    const real_T  *fs  = (const real_T *)mxGetData(PARAM_DEF0(S));
    const real_T  *DPhiMix  = (const real_T *)mxGetData(PARAM_DEF1(S));
    const real_T  *phiMix0  = (const real_T *)mxGetData(PARAM_DEF2(S));
    const real_T  *alpha  = (const real_T *)mxGetData(PARAM_DEF3(S));
	const real_T  *hn = (const real_T *)mxGetData(PARAM_DEF4(S));
    const real_T  *nStroke  = (const real_T *)mxGetData(PARAM_DEF9(S));

    ThdynCVNV2Zone_Update_wrapper(phi,FComb,combState,p,Tu,Fu,Vu,Tb,Fb,Vb,
            xC,p_prev,Tu_prev,Fu_prev,Ru_prev,uu_prev,Cvu_prev,
            Tb_prev,Fb_prev,Rb_prev,ub_prev,Cvb_prev,
            mCyl_prev,mbCyl_prev,VCyl_prev,QCyl_prev,HCyl_prev,WCyl_prev,
            mu_prev,mub_prev,Vu_prev,mfb_prev,
            mMix_prev,mb0,ResetMix,
            fs,p_width0,DPhiMix,p_width1,phiMix0,p_width2,
            alpha,p_width3,hn,p_width4,nStroke,p_width9);
}


/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
}
#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif


