/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  xxmextps.h
 *  subm:  NOx
 *  model: Engine20S-SCANIA_D12_2zoneFinal_for_submission
 *  expmt: Engine20S-SCANIA_D12_2zoneFinal_for_submission
 *  date:  March 13, 2015
 *  time:  1:19:24 pm
 *  user:  Norwegian University of Science and Technology
 *  from:  20-sim 4.5 Student License
 *  build: 4.5.1.5561
 **********************************************************/

#ifndef XX_MEXTPS_H
#define XX_MEXTPS_H

/* macro definition to get the current simulation time.
 * probably the double is not necessary.
 * use a global structure here which must be given the correct
 * value when this function is called.
 */
#define xx_time (XXDouble)ssGetT(MyS)
#define xx_major   ssIsMajorTimeStep(MyS)

#endif

